# Collective Communication Matmul
steps:
  - label: "Correctness tests for Collective Communication Matmul"
    key: "Collective_Communication_Matmul_CorrectnessTest"
    soft_fail: true
    agents:
      queue: tpu_v6e_queue
    commands:
      - .buildkite/scripts/run_in_docker.sh python3 -m pytest -s -v /workspace/tpu_inference/tests/kernels/collectives/all_gather_matmul_kernel_test.py
  - label: "Record correctness test result for Collective Communication Matmul"
    key: "record_Collective_Communication_Matmul_CorrectnessTest"
    depends_on: "Collective_Communication_Matmul_CorrectnessTest"
    env:
      CI_TARGET: "Collective Communication Matmul"
      CI_STAGE: "CorrectnessTest"
    agents:
      queue: tpu_v6e_queue
    commands:
      - |
        .buildkite/scripts/record_step_result.sh Collective_Communication_Matmul_CorrectnessTest
