# {FEATURE_NAME}
steps:
  - label: "Correctness tests for {FEATURE_NAME}"
    key: "{SANITIZED_FEATURE_NAME}_CorrectnessTest"
    soft_fail: true
    agents:
      queue: {QUEUE}
    commands:
      - echo "placeholder"  # TODO : replace with your correctness test command
  - label: "Record correctness test result for {FEATURE_NAME}"
    key: "record_{SANITIZED_FEATURE_NAME}_CorrectnessTest"
    depends_on: "{SANITIZED_FEATURE_NAME}_CorrectnessTest"
    env:
      CI_TARGET: "{FEATURE_NAME}"
      CI_STAGE: "CorrectnessTest"
    agents:
      queue: tpu_v6e_queue
    commands:
      - |
        .buildkite/scripts/record_step_result.sh {SANITIZED_FEATURE_NAME}_CorrectnessTest

  - label: "Performance tests for {FEATURE_NAME}"
    key: "{SANITIZED_FEATURE_NAME}_PerformanceTest"
    depends_on: "record_{SANITIZED_FEATURE_NAME}_CorrectnessTest"
    soft_fail: true
    agents:
      queue: {QUEUE}
    commands:
      - echo "placeholder"  # TODO : replace with your performance test command
  - label: "Record performance test result for {FEATURE_NAME}"
    key: "record_{SANITIZED_FEATURE_NAME}_PerformanceTest"
    depends_on: "{SANITIZED_FEATURE_NAME}_PerformanceTest"
    env:
      CI_TARGET: "{FEATURE_NAME}"
      CI_STAGE: "PerformanceTest"
    agents:
      queue: tpu_v6e_queue
    commands:
      - |
        .buildkite/scripts/record_step_result.sh {SANITIZED_FEATURE_NAME}_PerformanceTest
