# mla-w8a16
# kernel support matrix microbenchmarks
steps:
  - label: "Correctness tests for mla-w8a16"
    key: "mla-w8a16_CorrectnessTest"
    soft_fail: true
    agents:
      queue: tpu_v6e_queue
    commands:
      - |
        buildkite-agent meta-data set "mla-w8a16_CorrectnessTest" "to be added"
  - label: "Record correctness test result for mla-w8a16"
    key: "record_mla-w8a16_CorrectnessTest"
    depends_on: "mla-w8a16_CorrectnessTest"
    env:
      CI_TARGET: "mla-w8a16"
      CI_STAGE: "CorrectnessTest"
      CI_CATEGORY: "kernel support matrix microbenchmarks"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh mla-w8a16_CorrectnessTest

  - label: "Performance tests for mla-w8a16"
    key: "mla-w8a16_PerformanceTest"
    depends_on: "record_mla-w8a16_CorrectnessTest"
    soft_fail: true
    agents:
      queue: tpu_v6e_queue
    commands:
      - |
        buildkite-agent meta-data set "mla-w8a16_PerformanceTest" "to be added"
  - label: "Record performance test result for mla-w8a16"
    key: "record_mla-w8a16_PerformanceTest"
    depends_on: "mla-w8a16_PerformanceTest"
    env:
      CI_TARGET: "mla-w8a16"
      CI_STAGE: "PerformanceTest"
      CI_CATEGORY: "kernel support matrix microbenchmarks"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh mla-w8a16_PerformanceTest
