# CP
# parallelism support matrix
steps:
  - label: "${TEST_LABEL_PREFIX} Correctness tests for CP"
    key: "${TEST_KEY_PREFIX}CP_CorrectnessTest"
    soft_fail: true
    agents:
      queue: "${TPU_SMALL_CORE_QUEUE}"
    env:
      IS_FOR_V7X: "${IS_FOR_V7X}"
    commands:
      - |
        buildkite-agent meta-data set "CP_CorrectnessTest" "to be added"
  - label: "${TEST_LABEL_PREFIX} Record correctness test result for CP"
    key: "${TEST_KEY_PREFIX}record_CP_CorrectnessTest"
    depends_on: "${TEST_KEY_PREFIX}CP_CorrectnessTest"
    env:
      CI_TARGET: "${TEST_LABEL_PREFIX} CP"
      CI_STAGE: "CorrectnessTest"
      CI_CATEGORY: "parallelism support matrix"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TEST_KEY_PREFIX}CP_CorrectnessTest

  - label: "${TEST_LABEL_PREFIX} Performance tests for CP"
    key: "${TEST_KEY_PREFIX}CP_PerformanceTest"
    depends_on: "${TEST_KEY_PREFIX}record_CP_CorrectnessTest"
    soft_fail: true
    agents:
      queue: "${TPU_SMALL_CORE_QUEUE}"
    env:
      IS_FOR_V7X: "${IS_FOR_V7X}"
    commands:
      - |
        buildkite-agent meta-data set "CP_PerformanceTest" "to be added"
  - label: "${TEST_LABEL_PREFIX} Record performance test result for CP"
    key: "${TEST_KEY_PREFIX}record_CP_PerformanceTest"
    depends_on: "${TEST_KEY_PREFIX}CP_PerformanceTest"
    env:
      CI_TARGET: "${TEST_LABEL_PREFIX} CP"
      CI_STAGE: "PerformanceTest"
      CI_CATEGORY: "parallelism support matrix"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TEST_KEY_PREFIX}CP_PerformanceTest
