# CP
# parallelism support matrix
steps:
  - label: "Correctness tests for CP"
    key: "CP_CorrectnessTest"
    soft_fail: true
    agents:
      queue: tpu_v6e_queue
    commands:
      - |
        buildkite-agent meta-data set "CP_CorrectnessTest" "unverified"
  - label: "Record correctness test result for CP"
    key: "record_CP_CorrectnessTest"
    depends_on: "CP_CorrectnessTest"
    env:
      CI_TARGET: "CP"
      CI_STAGE: "CorrectnessTest"
      CI_CATEGORY: "parallelism support matrix"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh CP_CorrectnessTest

  - label: "Performance tests for CP"
    key: "CP_PerformanceTest"
    depends_on: "record_CP_CorrectnessTest"
    soft_fail: true
    agents:
      queue: tpu_v6e_queue
    commands:
      - |
        buildkite-agent meta-data set "CP_PerformanceTest" "unverified"
  - label: "Record performance test result for CP"
    key: "record_CP_PerformanceTest"
    depends_on: "CP_PerformanceTest"
    env:
      CI_TARGET: "CP"
      CI_STAGE: "PerformanceTest"
      CI_CATEGORY: "parallelism support matrix"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh CP_PerformanceTest
