# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# pipeline-name: EP
# pipeline-type: parallelism support matrix
steps:
  - label: "${TPU_VERSION:-tpu6e} Correctness tests for EP"
    key: "${TPU_VERSION:-tpu6e}_EP_CorrectnessTest"
    soft_fail: true
    agents:
      queue: "${TPU_QUEUE_MULTI:-tpu_v7x_8_queue}"
    env:
      IS_FOR_V7X: "${IS_FOR_V7X}"
    commands:
      - |
        .buildkite/scripts/run_in_docker.sh \
          bash /workspace/tpu_inference/tests/e2e/check_lm_eval.sh  --model_name "Qwen/Qwen1.5-MoE-A2.7B" --use_moe_ep_kernel 1 --tensor_parallel_size 4 --max_model_len 1024 --max_num_batched_tokens 128 --max_gen_toks 128 --enable_expert_parallel 1 --flex_threshold 0.37 --strict_threshold 0.38
      - |
        .buildkite/scripts/run_in_docker.sh \
          bash /workspace/tpu_inference/tests/e2e/check_lm_eval.sh  --model_name "Qwen/Qwen1.5-MoE-A2.7B" --use_moe_ep_kernel 0 --tensor_parallel_size 4 --max_model_len 1024 --max_num_batched_tokens 128 --max_gen_toks 128 --enable_expert_parallel 1 --flex_threshold 0.37 --strict_threshold 0.38
  - label: "${TPU_VERSION:-tpu6e} Record correctness test result for EP"
    key: "${TPU_VERSION:-tpu6e}_record_EP_CorrectnessTest"
    depends_on: "${TPU_VERSION:-tpu6e}_EP_CorrectnessTest"
    env:
      CI_TPU_VERSION: "${TPU_VERSION:-tpu6e}"
      CI_TARGET: "EP"
      CI_STAGE: "CorrectnessTest"
      CI_CATEGORY: "parallelism support matrix"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TPU_VERSION:-tpu6e}_EP_CorrectnessTest

  - label: "${TPU_VERSION:-tpu6e} Performance tests for EP"
    key: "${TPU_VERSION:-tpu6e}_EP_PerformanceTest"
    depends_on: "${TPU_VERSION:-tpu6e}_record_EP_CorrectnessTest"
    soft_fail: true
    agents:
      queue: "${TPU_QUEUE_MULTI:-tpu_v7x_8_queue}"
    env:
      IS_FOR_V7X: "${IS_FOR_V7X}"
    commands:
      - |
        .buildkite/scripts/run_in_docker.sh \
          bash -c 'python3 -m pytest -s -v -x /workspace/tpu_inference/tests/e2e/test_expert_parallel.py'
  - label: "${TPU_VERSION:-tpu6e} Record performance test result for EP"
    key: "${TPU_VERSION:-tpu6e}_record_EP_PerformanceTest"
    depends_on: "${TPU_VERSION:-tpu6e}_EP_PerformanceTest"
    env:
      CI_TPU_VERSION: "${TPU_VERSION:-tpu6e}"
      CI_TARGET: "EP"
      CI_STAGE: "PerformanceTest"
      CI_CATEGORY: "parallelism support matrix"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TPU_VERSION:-tpu6e}_EP_PerformanceTest
