# PP
# parallelism support matrix
steps:
  - label: "${TEST_LABEL_PREFIX} Correctness tests for PP"
    key: "${TEST_KEY_PREFIX}PP_CorrectnessTest"
    soft_fail: true
    agents:
      queue: "${TPU_SMALL_CORE_QUEUE}"
    env:
      IS_FOR_V7X: "${IS_FOR_V7X}"
    commands:
      - |
        .buildkite/scripts/run_in_docker.sh \
          python3 -m pytest -s -v /workspace/tpu_inference/tests/e2e/test_pipeline_parallel.py::test_pipeline_parallelism_jax_model \
          /workspace/tpu_inference/tests/e2e/test_pipeline_parallel.py::test_pipeline_parallelism_vllm_model \
          /workspace/tpu_inference/tests/e2e/test_pipeline_parallel.py::test_pipeline_parallelism_jax_model_correctness
  - label: "${TEST_LABEL_PREFIX} Record correctness test result for PP"
    key: "${TEST_KEY_PREFIX}record_PP_CorrectnessTest"
    depends_on: "${TEST_KEY_PREFIX}PP_CorrectnessTest"
    env:
      CI_TARGET: "${TEST_LABEL_PREFIX} PP"
      CI_STAGE: "CorrectnessTest"
      CI_CATEGORY: "parallelism support matrix"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TEST_KEY_PREFIX}PP_CorrectnessTest

  - label: "${TEST_LABEL_PREFIX} Performance tests for PP"
    key: "${TEST_KEY_PREFIX}PP_PerformanceTest"
    depends_on: "${TEST_KEY_PREFIX}record_PP_CorrectnessTest"
    soft_fail: true
    agents:
      queue: "${TPU_SMALL_CORE_QUEUE}"
    env:
      IS_FOR_V7X: "${IS_FOR_V7X}"
    commands:
      - |
        .buildkite/scripts/run_in_docker.sh \
          python3 -m pytest -s -v /workspace/tpu_inference/tests/e2e/test_pipeline_parallel.py::test_pipeline_parallelism_jax_model \
          /workspace/tpu_inference/tests/e2e/test_pipeline_parallel.py::test_pipeline_parallelism_vllm_model \
          /workspace/tpu_inference/tests/e2e/test_pipeline_parallel.py::test_pipeline_parallelism_jax_model_correctness
  - label: "${TEST_LABEL_PREFIX} Record performance test result for PP"
    key: "${TEST_KEY_PREFIX}record_PP_PerformanceTest"
    depends_on: "${TEST_KEY_PREFIX}PP_PerformanceTest"
    env:
      CI_TARGET: "${TEST_LABEL_PREFIX} PP"
      CI_STAGE: "PerformanceTest"
      CI_CATEGORY: "parallelism support matrix"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TEST_KEY_PREFIX}PP_PerformanceTest
