# Collective Communication Matmul
# kernel support matrix
steps:
  - label: "${TEST_LABEL_PREFIX} Correctness tests for Collective Communication Matmul"
    key: "${TEST_KEY_PREFIX}Collective_Communication_Matmul_CorrectnessTest"
    soft_fail: true
    agents:
      queue: "${TPU_SMALL_CORE_QUEUE}"
    env:
      IS_FOR_V7X: "${IS_FOR_V7X}"
    commands:
      - .buildkite/scripts/run_in_docker.sh python3 -m pytest -s -v /workspace/tpu_inference/tests/kernels/collectives/all_gather_matmul_kernel_test.py
  - label: "${TEST_LABEL_PREFIX} Record correctness test result for Collective Communication Matmul"
    key: "${TEST_KEY_PREFIX}record_Collective_Communication_Matmul_CorrectnessTest"
    depends_on: "${TEST_KEY_PREFIX}Collective_Communication_Matmul_CorrectnessTest"
    env:
      CI_TARGET: "${TEST_LABEL_PREFIX} Collective Communication Matmul"
      CI_STAGE: "CorrectnessTest"
      CI_CATEGORY: "kernel support matrix"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TEST_KEY_PREFIX}Collective_Communication_Matmul_CorrectnessTest

  - label: "${TEST_LABEL_PREFIX} Performance tests for Collective Communication Matmul"
    key: "${TEST_KEY_PREFIX}Collective_Communication_Matmul_PerformanceTest"
    depends_on: "${TEST_KEY_PREFIX}record_Collective_Communication_Matmul_CorrectnessTest"
    soft_fail: true
    agents:
      queue: "${TPU_SMALL_CORE_QUEUE}"
    env:
      IS_FOR_V7X: "${IS_FOR_V7X}"
    commands:
      - |
        buildkite-agent meta-data set "Collective_Communication_Matmul_PerformanceTest" "to be added"
  - label: "${TEST_LABEL_PREFIX} Record performance test result for Collective Communication Matmul"
    key: "${TEST_KEY_PREFIX}record_Collective_Communication_Matmul_PerformanceTest"
    depends_on: "${TEST_KEY_PREFIX}Collective_Communication_Matmul_PerformanceTest"
    env:
      CI_TARGET: "${TEST_LABEL_PREFIX} Collective Communication Matmul"
      CI_STAGE: "PerformanceTest"
      CI_CATEGORY: "kernel support matrix"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TEST_KEY_PREFIX}Collective_Communication_Matmul_PerformanceTest
