# DCN-based P/D disaggregation
# feature support matrix
steps:
  - label: "${TEST_LABEL_PREFIX} Correctness tests for DCN-based P/D disaggregation"
    key: "${TEST_KEY_PREFIX}DCN_based_P-D_disaggregation_CorrectnessTest"
    soft_fail: true
    agents:
      queue: "${TPU_SMALL_CORE_QUEUE}"
    env:
      IS_FOR_V7X: "${IS_FOR_V7X}"
    commands:
      - |
        buildkite-agent meta-data set "${TEST_KEY_PREFIX}DCN_based_P-D_disaggregation_CorrectnessTest" "unverified"
  - label: "${TEST_LABEL_PREFIX} Record correctness test result for DCN-based P/D disaggregation"
    key: "${TEST_KEY_PREFIX}record_DCN_based_P-D_disaggregation_CorrectnessTest"
    depends_on: "${TEST_KEY_PREFIX}DCN_based_P-D_disaggregation_CorrectnessTest"
    env:
      CI_TARGET: "${TEST_LABEL_PREFIX}DCN-based P/D disaggregation"
      CI_STAGE: "CorrectnessTest"
      CI_CATEGORY: "feature support matrix"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TEST_KEY_PREFIX}DCN_based_P-D_disaggregation_CorrectnessTest

  - label: "${TEST_LABEL_PREFIX} Performance tests for DCN-based P/D disaggregation"
    key: "${TEST_KEY_PREFIX}DCN_based_P-D_disaggregation_PerformanceTest"
    soft_fail: true
    env:
      IS_FOR_V7X: "${IS_FOR_V7X}"
      MODEL: "Qwen/Qwen3-0.6B"
      INPUT_LEN: 1024
      OUTPUT_LEN: 1024
      NUM_PROMPTS: 20
      RANDOM_SEED: 10
      MAX_CONCURRENCY: 1
    agents:
      queue: "${TPU_LARGE_CORE_QUEUE}"
    commands:
      - |
        .buildkite/scripts/run_disagg.sh

  - label: "${TEST_LABEL_PREFIX} Record performance test result for DCN-based P/D disaggregation"
    key: "${TEST_KEY_PREFIX}record_DCN_based_P-D_disaggregation_PerformanceTest"
    depends_on: "${TEST_KEY_PREFIX}DCN_based_P-D_disaggregation_PerformanceTest"
    env:
      CI_TARGET: "${TEST_LABEL_PREFIX}DCN-based P/D disaggregation"
      CI_STAGE: "PerformanceTest"
      CI_CATEGORY: "feature support matrix"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TEST_KEY_PREFIX}DCN_based_P-D_disaggregation_PerformanceTest
