# KV cache host offloading
# feature support matrix
steps:
  - label: "${TEST_LABEL_PREFIX} Correctness tests for KV cache host offloading"
    key: "${TEST_KEY_PREFIX}KV_Cache_Host_Offloading_CorrectnessTest"
    soft_fail: true
    agents:
      queue: "${TPU_SMALL_CORE_QUEUE}"
    env:
      IS_FOR_V7X: "${IS_FOR_V7X}"
    commands:
      - |
        buildkite-agent meta-data set "KV_Cache_Host_Offloading_CorrectnessTest" "to be added"
  - label: "${TEST_LABEL_PREFIX} Record correctness test result for KV cache host offloading"
    key: "${TEST_KEY_PREFIX}record_KV_Cache_Host_Offloading_CorrectnessTest"
    depends_on: "${TEST_KEY_PREFIX}KV_Cache_Host_Offloading_CorrectnessTest"
    env:
      CI_TARGET: "${TEST_LABEL_PREFIX} KV cache host offloading"
      CI_STAGE: "CorrectnessTest"
      CI_CATEGORY: "feature support matrix"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TEST_KEY_PREFIX}KV_Cache_Host_Offloading_CorrectnessTest

  - label: "${TEST_LABEL_PREFIX} Performance tests for KV cache host offloading"
    key: "${TEST_KEY_PREFIX}KV_Cache_Host_Offloading_PerformanceTest"
    depends_on: "${TEST_KEY_PREFIX}record_KV_Cache_Host_Offloading_CorrectnessTest"
    soft_fail: true
    agents:
      queue: "${TPU_SMALL_CORE_QUEUE}"
    env:
      IS_FOR_V7X: "${IS_FOR_V7X}"
    commands:
      - |
        buildkite-agent meta-data set "KV_Cache_Host_Offloading_PerformanceTest" "to be added"
  - label: "${TEST_LABEL_PREFIX} Record performance test result for KV cache host offloading"
    key: "${TEST_KEY_PREFIX}record_KV_Cache_Host_Offloading_PerformanceTest"
    depends_on: "${TEST_KEY_PREFIX}KV_Cache_Host_Offloading_PerformanceTest"
    env:
      CI_TARGET: "${TEST_LABEL_PREFIX} KV cache host offloading"
      CI_STAGE: "PerformanceTest"
      CI_CATEGORY: "feature support matrix"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TEST_KEY_PREFIX}KV_Cache_Host_Offloading_PerformanceTest
