# MLA
# kernel support matrix
steps:
  - label: "${TEST_LABEL_PREFIX} Correctness tests for MLA"
    key: "${TEST_KEY_PREFIX}MLA_CorrectnessTest"
    soft_fail: true
    agents:
      queue: "${TPU_SMALL_CORE_QUEUE}"
    env:
      IS_FOR_V7X: "${IS_FOR_V7X}"
    commands:
      - |
        buildkite-agent meta-data set "MLA_CorrectnessTest" "to be added"
  - label: "${TEST_LABEL_PREFIX} Record correctness test result for MLA"
    key: "${TEST_KEY_PREFIX}record_MLA_CorrectnessTest"
    depends_on: "${TEST_KEY_PREFIX}MLA_CorrectnessTest"
    env:
      CI_TARGET: "${TEST_LABEL_PREFIX} MLA"
      CI_STAGE: "CorrectnessTest"
      CI_CATEGORY: "kernel support matrix"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TEST_KEY_PREFIX}MLA_CorrectnessTest

  - label: "${TEST_LABEL_PREFIX} Performance tests for MLA"
    key: "${TEST_KEY_PREFIX}MLA_PerformanceTest"
    depends_on: "${TEST_KEY_PREFIX}record_MLA_CorrectnessTest"
    soft_fail: true
    agents:
      queue: "${TPU_SMALL_CORE_QUEUE}"
    env:
      IS_FOR_V7X: "${IS_FOR_V7X}"
    commands:
      - |
        buildkite-agent meta-data set "MLA_PerformanceTest" "to be added"
  - label: "${TEST_LABEL_PREFIX} Record performance test result for MLA"
    key: "${TEST_KEY_PREFIX}record_MLA_PerformanceTest"
    depends_on: "${TEST_KEY_PREFIX}MLA_PerformanceTest"
    env:
      CI_TARGET: "${TEST_LABEL_PREFIX} MLA"
      CI_STAGE: "PerformanceTest"
      CI_CATEGORY: "kernel support matrix"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TEST_KEY_PREFIX}MLA_PerformanceTest
