# MoE
# kernel support matrix
steps:
  - label: "${TEST_LABEL_PREFIX} Correctness tests for MoE"
    key: "${TEST_KEY_PREFIX}MoE_CorrectnessTest"
    soft_fail: true
    agents:
      queue: "${TPU_SMALL_CORE_QUEUE}"
    env:
      IS_FOR_V7X: "${IS_FOR_V7X}"
    commands:
      - |
        buildkite-agent meta-data set "${TEST_KEY_PREFIX}MoE_CorrectnessTest" "unverified"
  - label: "${TEST_LABEL_PREFIX} Record correctness test result for MoE"
    key: "${TEST_KEY_PREFIX}record_MoE_CorrectnessTest"
    depends_on: "${TEST_KEY_PREFIX}MoE_CorrectnessTest"
    env:
      CI_TARGET: "${TEST_LABEL_PREFIX}MoE"
      CI_STAGE: "CorrectnessTest"
      CI_CATEGORY: "kernel support matrix"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TEST_KEY_PREFIX}MoE_CorrectnessTest

  - label: "${TEST_LABEL_PREFIX} Performance tests for MoE"
    key: "${TEST_KEY_PREFIX}MoE_PerformanceTest"
    depends_on: "${TEST_KEY_PREFIX}record_MoE_CorrectnessTest"
    soft_fail: true
    agents:
      queue: "${TPU_SMALL_CORE_QUEUE}"
    env:
      IS_FOR_V7X: "${IS_FOR_V7X}"
    commands:
      - |
        buildkite-agent meta-data set "${TEST_KEY_PREFIX}MoE_PerformanceTest" "unverified"
  - label: "${TEST_LABEL_PREFIX} Record performance test result for MoE"
    key: "${TEST_KEY_PREFIX}record_MoE_PerformanceTest"
    depends_on: "${TEST_KEY_PREFIX}MoE_PerformanceTest"
    env:
      CI_TARGET: "${TEST_LABEL_PREFIX}MoE"
      CI_STAGE: "PerformanceTest"
      CI_CATEGORY: "kernel support matrix"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TEST_KEY_PREFIX}MoE_PerformanceTest
