# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  - label: "${TPU_VERSION:-tpu7x} Multi-host Disaggregation + Sampling Params Correctness"
    key: "${TPU_VERSION:-tpu7x}_multi_host_disagg_sampling_comb_CorrectnessTest"
    soft_fail: true
    agents:
      queue: default
    env:
      TPU_VERSION: "${TPU_VERSION:-tpu7x}"
      TEST_MODE: 2 # only run correctness test
    commands:
      - |
        .buildkite/e2e/run_multi_disagg_sampling_comb.sh

  - label: "${TPU_VERSION:-tpu7x} Record result for Multi-host Disagg + Sampling combination"
    key: "${TPU_VERSION:-tpu7x}_record_multi_host_disagg_sampling_comb_CorrectnessTest"
    depends_on: "${TPU_VERSION:-tpu7x}_multi_host_disagg_sampling_comb_CorrectnessTest"
    env:
      CI_TPU_VERSION: "${TPU_VERSION:-tpu7x}"
      CI_TARGET: "Multi-host Disagg + Sampling Params"
      CI_STAGE: "CorrectnessTest"
      CI_CATEGORY: "feature support matrix"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TPU_VERSION:-tpu7x}_multi_host_disagg_sampling_comb_CorrectnessTest
