# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# pipeline-name: multi-host
# pipeline-type: feature support matrix
steps: 
  - label: "${TPU_VERSION:-tpu7x} Correctness tests for multi-host"
    key: "${TPU_VERSION:-tpu7x}_multi-host_CorrectnessTest"
    soft_fail: true
    agents:
      queue: tpu_v7x_16_queue
    env:
      IS_FOR_V7X: "${IS_FOR_V7X}"
      HEAD_SSH_IP: ""
      HEAD_INTERNAL_IP: ""
      WORKER_SSH_IPS: ""
    commands:
      # Correctness Test Example:
      # 1. Start vLLM with specific model and tensor parallel size
      # 2. Run curl commands against it
      - |
        MODEL="gs://tpu-commons-ci/qwen/models--Qwen--Qwen3-30B-A3B/snapshots/ad44e777bcd18fa416d9da3bd8f70d33ebb85d39"
        .buildkite/scripts/run_multihost.sh \
          "vllm serve \${MODEL} \
            --port 8000 \
            --tensor-parallel-size 16 \
            --trust-remote-code \
            --max-model-len 1024 \
            --disable-log-requests \
            --no-async-scheduling \
            --load-format=runai_streamer \
            --no-enable-prefix-caching" \
          "curl http://localhost:8000/v1/completions \
            -X POST \
            -H 'Content-Type: application/json' \
            -d '{\"model\": \"${MODEL}\", \"prompt\": \"San Francisco is a\", \"max_tokens\": 50}'
          "
  - label: "${TPU_VERSION:-tpu7x} Record correctness test result for multi-host"
    key: "${TPU_VERSION:-tpu7x}_record_multi-host_CorrectnessTest"
    depends_on: "${TPU_VERSION:-tpu7x}_multi-host_CorrectnessTest"
    env:
      CI_TPU_VERSION: "${TPU_VERSION:-tpu7x}"
      CI_TARGET: "multi-host"
      CI_STAGE: "CorrectnessTest"
      CI_CATEGORY: "feature support matrix"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TPU_VERSION:-tpu7x}_multi-host_CorrectnessTest

  - label: "${TPU_VERSION:-tpu7x} Performance tests for multi-host"
    key: "${TPU_VERSION:-tpu7x}_multi-host_PerformanceTest"
    depends_on: "${TPU_VERSION:-tpu7x}_record_multi-host_CorrectnessTest"
    soft_fail: true
    agents:
      queue: tpu_v7x_16_queue
    commands:
      - buildkite-agent meta-data set "${TPU_VERSION:-tpu7x}_multi-host_PerformanceTest" "unverified"
  - label: "${TPU_VERSION:-tpu7x} Record performance test result for multi-host"
    key: "${TPU_VERSION:-tpu7x}_record_multi-host_PerformanceTest"
    depends_on: "${TPU_VERSION:-tpu7x}_multi-host_PerformanceTest"
    env:
      CI_TPU_VERSION: "${TPU_VERSION:-tpu7x}"
      CI_TARGET: "multi-host"
      CI_STAGE: "PerformanceTest"
      CI_CATEGORY: "feature support matrix"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TPU_VERSION:-tpu7x}_multi-host_PerformanceTest
