# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Out-of-tree model support
# feature support matrix
steps:
  - label: "Correctness tests for Out-of-tree model support"
    key: "out_of_tree_model_support_CorrectnessTest"
    soft_fail: true
    agents:
      queue: tpu_v6e_queue
    commands:
      - |
        .buildkite/scripts/run_in_docker.sh \
          python3 -m pytest -s -v /workspace/tpu_inference/tests/e2e/test_model_loader.py::test_register_model_success \
          /workspace/tpu_inference/tests/e2e/test_model_loader.py::test_registered_model_passes_vllm_interface_check

  - label: "Record correctness test result for Out-of-tree model support"
    key: "record_out_of_tree_model_support_CorrectnessTest"
    depends_on: "out_of_tree_model_support_CorrectnessTest"
    env:
      CI_TARGET: "Out-of-tree model support"
      CI_STAGE: "CorrectnessTest"
      CI_CATEGORY: "feature support matrix"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh out_of_tree_model_support_CorrectnessTest

  - label: "Performance tests for Out-of-tree model support"
    key: "out_of_tree_model_support_PerformanceTest"
    depends_on: "record_out_of_tree_model_support_CorrectnessTest"
    soft_fail: true
    agents:
      queue: tpu_v6e_queue
    commands:
      - |
        .buildkite/scripts/run_in_docker.sh \
          python3 -m pytest -s -v /workspace/tpu_inference/tests/e2e/test_model_loader.py::test_flax_nnx_vs_vllm_performance

  - label: "Record performance test result for Out-of-tree model support"
    key: "record_out_of_tree_model_support_PerformanceTest"
    depends_on: "out_of_tree_model_support_PerformanceTest"
    env:
      CI_TARGET: "Out-of-tree model support"
      CI_STAGE: "PerformanceTest"
      CI_CATEGORY: "feature support matrix"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh out_of_tree_model_support_PerformanceTest
