# Quantized Matmul
# kernel support matrix
steps:
  - label: "${TEST_LABEL_PREFIX} Correctness tests for Quantized Matmul"
    key: "${TEST_KEY_PREFIX}Quantized_Matmul_CorrectnessTest"
    soft_fail: true
    agents:
      queue: "${TPU_SMALL_CORE_QUEUE}"
    env:
      IS_FOR_V7X: "${IS_FOR_V7X}"
    commands:
      - |
        buildkite-agent meta-data set "Quantized_Matmul_CorrectnessTest" "to be added"
  - label: "${TEST_LABEL_PREFIX} Record correctness test result for Quantized Matmul"
    key: "${TEST_KEY_PREFIX}record_Quantized_Matmul_CorrectnessTest"
    depends_on: "${TEST_KEY_PREFIX}Quantized_Matmul_CorrectnessTest"
    env:
      CI_TARGET: "${TEST_LABEL_PREFIX} Quantized Matmul"
      CI_STAGE: "CorrectnessTest"
      CI_CATEGORY: "kernel support matrix"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TEST_KEY_PREFIX}Quantized_Matmul_CorrectnessTest

  - label: "${TEST_LABEL_PREFIX} Performance tests for Quantized Matmul"
    key: "${TEST_KEY_PREFIX}Quantized_Matmul_PerformanceTest"
    depends_on: "${TEST_KEY_PREFIX}record_Quantized_Matmul_CorrectnessTest"
    soft_fail: true
    agents:
      queue: "${TPU_SMALL_CORE_QUEUE}"
    env:
      IS_FOR_V7X: "${IS_FOR_V7X}"
    commands:
      - |
        buildkite-agent meta-data set "Quantized_Matmul_PerformanceTest" "to be added"
  - label: "${TEST_LABEL_PREFIX} Record performance test result for Quantized Matmul"
    key: "${TEST_KEY_PREFIX}record_Quantized_Matmul_PerformanceTest"
    depends_on: "${TEST_KEY_PREFIX}Quantized_Matmul_PerformanceTest"
    env:
      CI_TARGET: "${TEST_LABEL_PREFIX} Quantized Matmul"
      CI_STAGE: "PerformanceTest"
      CI_CATEGORY: "kernel support matrix"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TEST_KEY_PREFIX}Quantized_Matmul_PerformanceTest
