# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# pipeline-name: Speculative Decoding: Ngram
# pipeline-type: feature support matrix
steps:
  - label: "${TPU_VERSION:-tpu6e} Correctness tests for Speculative Decoding: Ngram"
    key: "${TPU_VERSION:-tpu6e}_Speculative_Decoding-_Ngram_CorrectnessTest"
    soft_fail: true
    agents:
      queue: "${TPU_QUEUE_SINGLE:-tpu_v6e_queue}"
    env:
      IS_FOR_V7X: "${IS_FOR_V7X}"
    commands:
      - |
        .buildkite/scripts/run_in_docker.sh \
          python3 -m pytest -s -v /workspace/tpu_inference/tests/e2e/test_speculative_decoding.py::test_ngram_correctness_greedy \
          /workspace/tpu_inference/tests/e2e/test_speculative_decoding.py::test_ngram_correctness_random
  - label: "${TPU_VERSION:-tpu6e} Record correctness test result for Speculative Decoding: Ngram"
    key: "${TPU_VERSION:-tpu6e}_record_Speculative_Decoding-_Ngram_CorrectnessTest"
    depends_on: "${TPU_VERSION:-tpu6e}_Speculative_Decoding-_Ngram_CorrectnessTest"
    env:
      CI_TPU_VERSION: "${TPU_VERSION:-tpu6e}"
      CI_TARGET: "Speculative Decoding: Ngram"
      CI_STAGE: "CorrectnessTest"
      CI_CATEGORY: "feature support matrix"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TPU_VERSION:-tpu6e}_Speculative_Decoding-_Ngram_CorrectnessTest

  - label: "${TPU_VERSION:-tpu6e} Performance tests for Speculative Decoding: Ngram"
    key: "${TPU_VERSION:-tpu6e}_Speculative_Decoding-_Ngram_PerformanceTest"
    depends_on: "${TPU_VERSION:-tpu6e}_record_Speculative_Decoding-_Ngram_CorrectnessTest"
    soft_fail: true
    agents:
      queue: "${TPU_QUEUE_SINGLE:-tpu_v6e_queue}"
    env:
      IS_FOR_V7X: "${IS_FOR_V7X}"
    commands:
      - |
        .buildkite/scripts/run_in_docker.sh \
          python3 -m pytest -s -v /workspace/tpu_inference/tests/e2e/test_speculative_decoding.py::test_ngram_performance_greedy \
          /workspace/tpu_inference/tests/e2e/test_speculative_decoding.py::test_ngram_performance_random

  - label: "${TPU_VERSION:-tpu6e} Record performance test result for Speculative Decoding: Ngram"
    key: "${TPU_VERSION:-tpu6e}_record_Speculative_Decoding-_Ngram_PerformanceTest"
    depends_on: "${TPU_VERSION:-tpu6e}_Speculative_Decoding-_Ngram_PerformanceTest"
    env:
      CI_TPU_VERSION: "${TPU_VERSION:-tpu6e}"
      CI_TARGET: "Speculative Decoding: Ngram"
      CI_STAGE: "PerformanceTest"
      CI_CATEGORY: "feature support matrix"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TPU_VERSION:-tpu6e}_Speculative_Decoding-_Ngram_PerformanceTest
