# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

x-run-condition: &run-on-nightly-or-tag
  if: build.env("NIGHTLY") == "1" || build.tag =~ /^v?[0-9]+(\.[a-zA-Z0-9]+)*([a-zA-Z]+[0-9]*)?$/

notify:
  - email: "ullm-test-notifications-external@google.com"
    if: build.state == "failed" && build.branch == "main"
  - slack: "vllm#tpu-ci-notifications"
    if: build.state == "failed" && build.branch == "main"

steps:
   - label: "Upload Tests for Models & Features"
     <<: *run-on-nightly-or-tag
     agents:
       queue: cpu
     commands:
       - bash .buildkite/scripts/upload_models_and_features.sh

   - wait: ~
     continue_on_failure: true  # ensure we still generate support matrices even if some tests fail

   - label: "Generate support matrices"
     <<: *run-on-nightly-or-tag
     key: generate_support_matrices
     agents:
       queue: cpu
     soft_fail: true
     commands:
       - bash .buildkite/scripts/generate_support_matrices.sh

   - label: "Commit support matrices if is nightly build or release tag specified"
    #  <<: *run-on-nightly-or-tag
     if: build.env("BUILDKITE_BRANCH") == "main" && (build.env("NIGHTLY") == "1" || build.tag =~ /^v?[0-9]+(\.[a-zA-Z0-9]+)*([a-zA-Z]+[0-9]*)?$/)
     key: commit_support_matrices
     depends_on: generate_support_matrices
     agents:
       queue: cpu
     secrets:
      - GITHUB_PAT
     command:
       - bash .buildkite/scripts/commit_support_matrices.sh

  #  - label: "Notify test results"
  #    <<: *run-on-nightly-or-tag
  #    key: notify_test_results
  #    depends_on: commit_support_matrices
  #    agents:
  #      queue: cpu
  #    commands:
  #      - bash .buildkite/scripts/notify_test_results.sh

  #  - label: "Record verified commit hashes"
  #    if: build.env("NIGHTLY") == "1"
  #    key: record_verified_commit_hashes
  #    depends_on:
  #      - notify_test_results
  #      - tpu_test_notification
  #    agents:
  #      queue: cpu
  #    secrets:
  #     - GITHUB_PAT
  #    command:
  #      - bash .buildkite/scripts/commit_verified_commit_hashes.sh
