steps:
  - label: ":docker: Build base image (tpu7x)"
    key: tpu7x_build_docker
    agents:
      queue: cpu_64_core
    env:
      TPU_VERSION: "tpu7x"
    commands:
      - bash -c 'source .buildkite/scripts/setup_docker_env.sh && setup_environment "vllm-tpu" "false" "true"'

  - label: "tpu7x Multimodal Inputs (fix validation)"
    key: tpu7x_multimodal
    depends_on: tpu7x_build_docker
    agents:
      queue: tpu_v7x_2_queue
    env:
      USE_PREBUILT_IMAGE: "1"
      TPU_VERSION: "tpu7x"
    commands:
      - .buildkite/scripts/run_in_docker.sh python3 -m pytest -s -v /workspace/tpu_inference/tests/e2e/test_multi_modal_inference.py
