steps:
  # -----------------------------------------------------------------
  # TEST STEPS - Calling wrapper, using python3 -m pytest
  # -----------------------------------------------------------------
   - label: "TPU Test 0: test_perf.py"
     key: tpu_test_0
     soft_fail: true
     agents:
       queue: tpu_v6e_queue
     commands:
       - .buildkite/scripts/run_in_docker.sh python3 -m pytest -s -v /workspace/vllm/tests/v1/tpu/test_perf.py

   - label: "TPU Test 1: test_compilation.py"
     key: tpu_test_1
     soft_fail: true
     agents:
       queue: tpu_v6e_queue
     commands:
       - .buildkite/scripts/run_in_docker.sh python3 -m pytest -s -v /workspace/vllm/tests/tpu/test_compilation.py

   - label: "TPU Test 2: test_basic.py"
     key: tpu_test_2
     soft_fail: true
     agents:
       queue: tpu_v6e_queue
     commands:
       - .buildkite/scripts/run_in_docker.sh python3 -m pytest -s -v /workspace/vllm/tests/v1/tpu/test_basic.py

   - label: "TPU Test 3: test_accuracy.py (v1)"
     key: tpu_test_3
     soft_fail: true
     agents:
       queue: tpu_v6e_queue
     commands:
       - .buildkite/scripts/run_in_docker.sh python3 -m pytest -s -v /workspace/vllm/tests/entrypoints/llm/test_accuracy.py::test_lm_eval_accuracy_v1_engine

   - label: "TPU Test 4: test_quantization_accuracy.py"
     key: tpu_test_4
     soft_fail: true
     agents:
       queue: tpu_v6e_queue
     commands:
       - .buildkite/scripts/run_in_docker.sh python3 -m pytest -s -v /workspace/vllm/tests/tpu/test_quantization_accuracy.py

   - label: "TPU Test 5: examples/offline_inference/tpu.py"
     key: tpu_test_5
     soft_fail: true
     agents:
       queue: tpu_v6e_queue
     commands:
       - .buildkite/scripts/run_in_docker.sh python3 /workspace/vllm/examples/offline_inference/tpu.py

   - label: "TPU Test 6: test_tpu_model_runner.py"
     key: tpu_test_6
     soft_fail: true
     agents:
       queue: tpu_v6e_queue
     commands:
       - .buildkite/scripts/run_in_docker.sh python3 -m pytest -s -v /workspace/vllm/tests/v1/tpu/worker/test_tpu_model_runner.py

   - label: "TPU Test 7: test_sampler.py"
     key: tpu_test_7
     soft_fail: true
     agents:
       queue: tpu_v6e_queue
     commands:
       - .buildkite/scripts/run_in_docker.sh python3 -m pytest -s -v /workspace/vllm/tests/v1/tpu/test_sampler.py

   - label: "TPU Test 8: test_topk_topp_sampler.py"
     key: tpu_test_8
     soft_fail: true
     agents:
       queue: tpu_v6e_queue
     commands:
       - .buildkite/scripts/run_in_docker.sh python3 -m pytest -s -v /workspace/vllm/tests/v1/tpu/test_topk_topp_sampler.py

   - label: "TPU Test 9: test_multimodal.py"
     key: tpu_test_9
     soft_fail: true
     agents:
       queue: tpu_v6e_queue
     commands:
       - .buildkite/scripts/run_in_docker.sh python3 -m pytest -s -v /workspace/vllm/tests/v1/tpu/test_multimodal.py

   - label: "TPU Test 10: test_pallas.py"
     key: tpu_test_10
     soft_fail: true
     agents:
       queue: tpu_v6e_queue
     commands:
       - .buildkite/scripts/run_in_docker.sh python3 -m pytest -s -v /workspace/vllm/tests/v1/tpu/test_pallas.py

   - label: "TPU Test 11: test_struct_output_generate.py"
     key: tpu_test_11
     soft_fail: true
     agents:
       queue: tpu_v6e_queue
     commands:
       - .buildkite/scripts/run_in_docker.sh python3 -m pytest -s -v /workspace/vllm/tests/v1/entrypoints/llm/test_struct_output_generate.py

   - label: "TPU Test 12: test_moe_pallas.py"
     key: tpu_test_12
     soft_fail: true
     agents:
       queue: tpu_v6e_queue
     commands:
      - .buildkite/scripts/run_in_docker.sh python3 -m pytest -s -v /workspace/vllm/tests/tpu/test_moe_pallas.py

   - label: "TPU Test 13: ragged_paged_attention_test.py"
     key: tpu_test_13
     soft_fail: true
     agents:
       queue: tpu_v6e_queue
     commands:
       - .buildkite/scripts/run_in_docker.sh python3 -m pytest -s -v /workspace/tpu_commons/tests/ragged_paged_attention_test.py

  # -----------------------------------------------------------------
  # NOTIFICATION STEP
  # -----------------------------------------------------------------
   - label: "TPU V1 Test Notification"
     depends_on:
       - tpu_test_0
       - tpu_test_1
       - tpu_test_2
       - tpu_test_3
       - tpu_test_4
       - tpu_test_5
       - tpu_test_6
       - tpu_test_7
       - tpu_test_8
       - tpu_test_9
       - tpu_test_10
       - tpu_test_11
       - tpu_test_12
       - tpu_test_13
     agents:
       queue: tpu_v6e_queue
     commands: "bash .buildkite/scripts/check_results.sh"
