# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  - group: "${TESTS_GROUP_LABEL:-[jax] TPU6e Tests Group}"
    steps:

      # -----------------------------------------------------------------
      # Centralized Build Step (Runs on the CPU queue)
      # -----------------------------------------------------------------
      - label: ":docker: Build and Push Base Image (${TPU_VERSION:-tpu6e})"
        key: "${TPU_VERSION:-tpu6e}_build_docker"
        agents:
          queue: cpu_64_core
        env:
          TPU_VERSION: "${TPU_VERSION:-tpu6e}"
        commands:
          - bash -c 'source .buildkite/scripts/setup_docker_env.sh && setup_environment "vllm-tpu" "false" "true"'

      - label: "${TPU_VERSION:-tpu6e} E2E test for Single Host DCN-based P/D disaggregation"
        key: ${TPU_VERSION:-tpu6e}_test_34
        depends_on: "${TPU_VERSION:-tpu6e}_build_docker"
        soft_fail: true
        env:
          USE_PREBUILT_IMAGE: "1"
          TPU_VERSION: "${TPU_VERSION:-tpu6e}"
          MODEL: "Qwen/Qwen3-0.6B"
          INPUT_LEN: 512
          OUTPUT_LEN: 128
          NUM_PROMPTS: 200
          REQUEST_RATE: 4
        agents:
          queue: "${TPU_QUEUE_MULTI:-tpu_v6e_8_queue}"
        commands:
          - |
            .buildkite/scripts/run_in_docker.sh bash /workspace/tpu_inference/examples/disagg/run_disagg_single_host.sh

      # -----------------------------------------------------------------
      # NOTIFICATION STEP
      # -----------------------------------------------------------------
      - label: "${TPU_VERSION:-tpu6e} TPU Test Notification"
        key: ${TPU_VERSION:-tpu6e}_tpu_test_notification
        depends_on:
          - ${TPU_VERSION:-tpu6e}_test_34
        agents:
          queue: cpu
        commands:
          - |
            .buildkite/scripts/check_results.sh \
              "TPU JAX Tests Failed" ${TPU_VERSION:-tpu6e}_test_0 ${TPU_VERSION:-tpu6e}_test_1 ${TPU_VERSION:-tpu6e}_test_2 ${TPU_VERSION:-tpu6e}_test_3 ${TPU_VERSION:-tpu6e}_test_4 ${TPU_VERSION:-tpu6e}_test_6 ${TPU_VERSION:-tpu6e}_test_7_1 ${TPU_VERSION:-tpu6e}_test_7_2 ${TPU_VERSION:-tpu6e}_test_7_3 ${TPU_VERSION:-tpu6e}_test_8 ${TPU_VERSION:-tpu6e}_test_9 ${TPU_VERSION:-tpu6e}_test_10 ${TPU_VERSION:-tpu6e}_test_11 ${TPU_VERSION:-tpu6e}_test_12 ${TPU_VERSION:-tpu6e}_test_13 ${TPU_VERSION:-tpu6e}_test_15 ${TPU_VERSION:-tpu6e}_test_16 ${TPU_VERSION:-tpu6e}_test_17 ${TPU_VERSION:-tpu6e}_test_18 ${TPU_VERSION:-tpu6e}_test_19 ${TPU_VERSION:-tpu6e}_test_20 ${TPU_VERSION:-tpu6e}_test_21 ${TPU_VERSION:-tpu6e}_test_22 ${TPU_VERSION:-tpu6e}_test_23 ${TPU_VERSION:-tpu6e}_test_24 ${TPU_VERSION:-tpu6e}_test_25 ${TPU_VERSION:-tpu6e}_test_26 ${TPU_VERSION:-tpu6e}_test_27 ${TPU_VERSION:-tpu6e}_test_28 ${TPU_VERSION:-tpu6e}_test_29 ${TPU_VERSION:-tpu6e}_test_30 ${TPU_VERSION:-tpu6e}_test_31 ${TPU_VERSION:-tpu6e}_test_32 ${TPU_VERSION:-tpu6e}_test_33 ${TPU_VERSION:-tpu6e}_test_34
