steps:
  # -----------------------------------------------------------------
  # TEST STEPS - Calling wrapper
  # -----------------------------------------------------------------
   - label: "E2E MLPerf tests for JAX models"
     key: test_0
     soft_fail: true
     agents:
       queue: tpu_v6e_queue
     commands:
       - .buildkite/scripts/run_in_docker.sh bash /workspace/tpu_commons/tests/e2e/benchmarking/mlperf.sh

   - label: "E2E MLPerf tests for JAX + vLLM models"
     key: test_1
     soft_fail: true
     env:
       MODEL_IMPL_TYPE: "vllm"
     agents:
       queue: tpu_v6e_queue
     commands:
       - .buildkite/scripts/run_in_docker.sh bash /workspace/tpu_commons/tests/e2e/benchmarking/mlperf.sh
       - .buildkite/scripts/run_in_docker.sh python3 -m pytest -s -v /workspace/tpu_commons/tests/test_lora.py

   - label: "JAX unit tests"
     key: test_2
     soft_fail: true
     agents:
       queue: tpu_v6e_queue
     commands:
       - |
         .buildkite/scripts/run_in_docker.sh \
           python3 -m pytest -s -v /workspace/tpu_commons/tests/ \
           --ignore=/workspace/tpu_commons/tests/kernels/ragged_paged_attention_kernel_v3_test.py \
           --cov tpu_commons --cov-report term-missing --cov-fail-under=75

   - label: "E2E MLPerf tests for JAX models with quantization"
     key: test_3
     soft_fail: true
     env:
       TPU_BACKEND_TYPE: "jax"
       QUANTIZATION: "True"
     agents:
       queue: tpu_v6e_queue
     commands:
       - .buildkite/scripts/run_in_docker.sh bash /workspace/tpu_commons/tests/e2e/benchmarking/mlperf.sh

   - label: "E2E MLPerf tests for JAX new models"
     key: test_4
     soft_fail: true
     env:
       NEW_MODEL_DESIGN: "True"
     agents:
       queue: tpu_v6e_queue
     commands:
       - .buildkite/scripts/run_in_docker.sh bash /workspace/tpu_commons/tests/e2e/benchmarking/mlperf.sh

  # -----------------------------------------------------------------
  # NOTIFICATION STEP
  # -----------------------------------------------------------------
   - label: "TPU Test Notification"
     depends_on:
       - test_0
       - test_1
       - test_2
       - test_3
       - test_4
     agents:
       queue: tpu_v6e_queue
     commands: "bash .buildkite/scripts/check_results.sh 'TPU JAX Tests Failed' test_0 test_1 test_2 test_3 test_4"
