steps:
  # -----------------------------------------------------------------
  # TEST STEPS - Calling wrapper
  # -----------------------------------------------------------------
   - label: "ragged_paged_attention_test.py"
     key: tpu_test_0
     soft_fail: true
     env:
       TPU_BACKEND_TYPE: "jax"
       MODEL_IMPL_TYPE: "n/a"
     agents:
       queue: tpu_v6e_queue
     commands:
       - .buildkite/scripts/run_in_docker.sh python3 -m pytest -s -v /workspace/tpu_commons/tests/ragged_paged_attention_test.py
       - .buildkite/scripts/run_in_docker.sh python3 -m pytest -s -v /workspace/tpu_commons/tests/ragged_kv_cache_update_test.py

   - label: "benchmarking/mmlu.sh for JAX + FlaxNNX models"
     key: tpu_test_1_model_impl_flax_nnx
     soft_fail: true
     env:
       TPU_BACKEND_TYPE: "jax"
       MODEL_IMPL_TYPE: "flax_nnx"
     agents:
       queue: tpu_v6e_queue
     commands:
       - .buildkite/scripts/run_in_docker.sh bash /workspace/tpu_commons/tests/e2e/benchmarking/mmlu.sh

   - label: "benchmarking/mmlu.sh for JAX + vLLM models"
     key: tpu_test_1_model_impl_vllm
     soft_fail: true
     env:
       TPU_BACKEND_TYPE: "jax"
       MODEL_IMPL_TYPE: "vllm"
     agents:
       queue: tpu_v6e_queue
     commands:
       - .buildkite/scripts/run_in_docker.sh bash /workspace/tpu_commons/tests/e2e/benchmarking/mmlu.sh

  # -----------------------------------------------------------------
  # NOTIFICATION STEP
  # -----------------------------------------------------------------
   - label: "TPU Test Notification"
     depends_on:
       - tpu_test_0
       - tpu_test_1_model_impl_flax_nnx
       - tpu_test_1_model_impl_vllm
     agents:
       queue: tpu_v6e_queue
     commands: "bash .buildkite/scripts/check_results.sh"
