# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# x-run-condition: &run-on-nightly-or-tag
#   if: build.env("NIGHTLY") == "1" || build.tag =~ /^v?[0-9]+(\.[a-zA-Z0-9]+)*([a-zA-Z]+[0-9]*)?$/



# 1. Build image (combire create_job.sh and build_image.sh)
# 2. Scan csv file
# 3. publish job and generate pipeline step (include execute bm and report result)

steps:
   - label: "Build vllm-tpu image"
     key: "build-vllm-tpu-image"
     agents:
       queue: cpu
     env:
       GCP_PROJECT_ID: "cloud-tpu-inference-test"
       GCP_REGION: "southamerica-west1"
       ARTIFACT_REPO: "vllm-tpu-bm-bk"
     commands:
       - VLLM_COMMIT_HASH=$$(buildkite-agent meta-data get 'VLLM_COMMIT_HASH')
       - VLLM_SHORT_HASH=$$(buildkite-agent meta-data get 'VLLM_SHORT_HASH')
       - TPU_SHORT_HASH=$$(buildkite-agent meta-data get 'TPU_SHORT_HASH')
       - CODE_HASH=$$(buildkite-agent meta-data get 'CODE_HASH')
       - echo "CodeHash - $${CODE_HASH}"
      #  - bash .buildkite/hourly_benchmark/scripts/build_tpu_inference_image.sh $$VLLM_COMMIT_HASH $$BUILDKITE_COMMIT

   - label: "Read CSV file and publish benchmark job"
     key: "read-csv-publish-job"
     depends_on: "build-vllm-tpu-image"
     agents:
       queue: cpu
     env:
       # Temp hack when dev
       TPU_IMAGE: "vllm-tpu:64a40a7ab4d0053830fae04c83763fa67f2183e6-32d1ad9716eb2d70354de84b46be7ea85fa61c85-"
       GCP_PROJECT_ID: "cloud-tpu-inference-test"
       GCP_REGION: "southamerica-west1"
       ARTIFACT_REPO: "vllm-tpu-bm-bk"
       GCP_INSTANCE_ID: "vllm-bm-inst"
       GCP_DATABASE_ID: "vllm-bm-bk-runs"
     commands:
       - VLLM_COMMIT_HASH=$$(buildkite-agent meta-data get 'VLLM_COMMIT_HASH')
       - VLLM_SHORT_HASH=$$(buildkite-agent meta-data get 'VLLM_SHORT_HASH')
       - TPU_SHORT_HASH=$$(buildkite-agent meta-data get 'TPU_SHORT_HASH')
       - CODE_HASH=$$(buildkite-agent meta-data get 'CODE_HASH')
       - echo "CodeHash - $${CODE_HASH}"
      #  - bash .buildkite/hourly_benchmark/scripts/daily_benchmark.sh $$VLLM_COMMIT_HASH $$BUILDKITE_COMMIT
      # .buildkite/hourly_benchmark/cases/hourly_jax_dev.csv 

  #  - wait: ~
  #    continue_on_failure: true  # ensure we still generate support matrices even if some tests fail
   - label: "Publish: benchmark - RecordId: 68db88d5-80e6-4973-9d24-0dbcea35cc59"
     depends_on: "read-csv-publish-job"
     env:
       GCP_PROJECT_ID: "cloud-tpu-inference-test"
       GCP_REGION: "southamerica-west1"
       GCS_BUCKET: "vllm-cb-storage2"
       ARTIFACT_REPO: "vllm-tpu-bm-bk"
       GCP_INSTANCE_ID: "vllm-bm-inst"
       GCP_DATABASE_ID: "vllm-bm-bk-runs"
     agents:
       queue: tpu_v6e_queue
     command:
      #  - CODE_HASH=$$(buildkite-agent meta-data get 'CODE_HASH')
       - CODE_HASH="4c4b6f7a9-4e6e6fb4-"
       - ".buildkite/benchmark/scripts/agent/run_job.sh 68db88d5-80e6-4973-9d24-0dbcea35cc59"
