steps:
  # -----------------------------------------------------------------
  # TEST STEPS - Calling wrapper
  # -----------------------------------------------------------------
   - label: "E2E MLPerf tests for JAX models"
     key: test_0
     soft_fail: true
     agents:
       queue: tpu_v6e_queue
     commands:
       - .buildkite/scripts/run_in_docker.sh bash /workspace/tpu_commons/tests/e2e/benchmarking/mlperf.sh

   - label: "E2E MLPerf tests for JAX + vLLM models"
     key: test_1
     soft_fail: true
     env:
       MODEL_IMPL_TYPE: "vllm"
     agents:
       queue: tpu_v6e_queue
     commands:
       - .buildkite/scripts/run_in_docker.sh bash /workspace/tpu_commons/tests/e2e/benchmarking/mlperf.sh

   - label: "JAX unit tests"
     key: test_2
     soft_fail: true
     agents:
       queue: tpu_v6e_queue
     commands:
       - |
         .buildkite/scripts/run_in_docker.sh \
           python3 -m pytest -s -v /workspace/tpu_commons/tests/ \
           --deselect=/workspace/tpu_commons/tests/models/jax/test_model_loader.py::test_get_vllm_model \
           --ignore=/workspace/tpu_commons/tests/models/vllm \
           --ignore=/workspace/tpu_commons/tests/e2e/test_multi_modal_inference.py \
           --cov-config=/workspace/tpu_commons/.coveragerc --cov tpu_commons --cov-report term-missing --cov-fail-under=75

   - label: "E2E MLPerf tests for JAX models with quantization"
     key: test_3
     soft_fail: true
     env:
       TPU_BACKEND_TYPE: "jax"
       QUANTIZATION: "True"
     agents:
       queue: tpu_v6e_queue
     commands:
       - .buildkite/scripts/run_in_docker.sh bash /workspace/tpu_commons/tests/e2e/benchmarking/mlperf.sh

   - label: "E2E MLPerf tests for JAX new models"
     key: test_4
     soft_fail: true
     env:
       NEW_MODEL_DESIGN: "True"
     agents:
       queue: tpu_v6e_queue
     commands:
       - .buildkite/scripts/run_in_docker.sh bash /workspace/tpu_commons/tests/e2e/benchmarking/mlperf.sh


   - label: "E2E MLperf tests for Llama4 models"
     key: test_5
     soft_fail: true
     env:
       NEW_MODEL_DESIGN: "True"
       USE_V6E8_QUEUE: "True"
     agents:
       queue: tpu_v6e_8_queue
     commands:
       - .buildkite/scripts/run_in_docker.sh bash /workspace/tpu_commons/tests/e2e/benchmarking/mlperf.sh


   - label: "E2E offline inference test"
     key: test_6
     soft_fail: true
     agents:
       queue: tpu_v6e_queue
     commands:
       - |
         .buildkite/scripts/run_in_docker.sh \
           python3 -m pytest -s -v /workspace/tpu_commons/tests/e2e/test_multi_modal_inference.py


  # -----------------------------------------------------------------
  # NOTIFICATION STEP
  # -----------------------------------------------------------------
   - label: "TPU Test Notification"
     depends_on:
       - test_0
       - test_1
       - test_2
       - test_3
       - test_4
       - test_5
       - test_6
     agents:
       queue: tpu_v6e_queue
     commands: "bash .buildkite/scripts/check_results.sh 'TPU JAX Tests Failed' test_0 test_1 test_2 test_3 test_4 test_5 test_6"
