# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  - label: "Run Benchmarks For Collecting Tuning Cases"
    agents:
      queue: cpu
    priority: 200
    key: kernel_cases_collection
    depends_on: "build_docker"
    command: |
      source .buildkite/benchmark/scripts/kernel_auto_tune.sh
      setup_autotune_envs "PRE_KERNEL_AUTOTUNE_CASES_COLLECTION"
      bash .buildkite/benchmark/scripts/benchmark_bootstrap.sh kernel_cases_collection
      # Upload another step as a barrier to ensure that kernel tuning cases collections is not invoked before all benchmark cases are collected and uploaded.
      DEPENDS_ON_BLOCK="$(setup_depends_on_block '', 'kernel_cases_collection')"

      cat <<EOT | buildkite-agent pipeline upload
      steps:
        - label: "Barrier Step for Invoking Kernel Tuners"
          key: pre_autotune_bm_barrier
          priority: 200
          depends_on:$$DEPENDS_ON_BLOCK
          commands:
            - |
              echo "🚀 Barrier step for invoking kernel tuners after all benchmark cases are collected and uploaded."
      EOT

  - label: "Upload Kernel Tuner Invocation Step"
    key: upload_invoke_kernel_tuners
    priority: 200
    agents:
      queue: cpu
    depends_on:
      - "pre_autotune_bm_barrier"
    command: |
      source .buildkite/benchmark/scripts/kernel_auto_tune.sh
      setup_autotune_envs "GENERATE_KERNEL_AUTOTUNE_CASES"
      DEPENDS_ON_BLOCK="$(setup_depends_on_block '' 'kernel_cases_collection')"

      cat <<EOT | buildkite-agent pipeline upload
      steps:
        - label: "Invoke Kernel Tuners"
          key: invoke_kernel_tuners
          priority: 200
          depends_on:$$DEPENDS_ON_BLOCK
          env:
            USE_PREBUILT_IMAGE: "1"
            TPU_VERSION: "tpu6e"
            KERNEL_AUTOTUNE_ID: "$$KERNEL_AUTOTUNE_ID"
          secrets:
            - GITHUB_PAT
          agents:
            queue: tpu_v6e_queue
          commands:
            - |
              rm -f /tmp/kernel_tuning/generated_pipeline.yml
            - |
              .buildkite/scripts/run_in_docker.sh bash -c 'pip install --upgrade google-cloud-spanner google-api-core google-auth absl-py && python3 -m tools.kernel.tuner.v1.autotune.kernel_auto_tune_invoker --auto_tune_id=$$KERNEL_AUTOTUNE_ID'
            - |
              # Upload the generated pipeline YAML from the temp dir on the host.
              buildkite-agent artifact upload "/tmp/kernel_tuning/generated_pipeline.yml"
              echo "Upload generated pipeline YAML to Buildkite artifacts with priority ${PRIORITY_KERNEL_TUNING}"
              {
                echo "priority: ${PRIORITY_KERNEL_TUNING}";
                cat /tmp/kernel_tuning/generated_pipeline.yml;
              } | buildkite-agent pipeline upload
      EOT

  - label: "Re-Run Benchmarks For Evaluating Tuning Results"
    agents:
      queue: cpu
    priority: 200
    key: rerun_benchmarks_for_post_kernel_autotune_evaluation
    depends_on: patch_kernel_autotune_result 
    command: |
      source .buildkite/benchmark/scripts/kernel_auto_tune.sh
      setup_autotune_envs "POST_KERNEL_AUTOTUNE_BM_RERUN"
      bash .buildkite/benchmark/scripts/benchmark_bootstrap.sh invoke_kernel_autotune_result_evaluation
      DEPENDS_ON_BLOCK="$(setup_depends_on_block '' 'rerun_benchmarks_for_post_kernel_autotune_evaluation')"

      cat <<EOT | buildkite-agent pipeline upload
      steps:
        - label: "Evaluate Kernel Autotune Results And May Create PR"
          key: evaluate_kernel_autotune_results_and_may_create_pr
          priority: 200
          depends_on:$$DEPENDS_ON_BLOCK
          commands:
            - |
              echo "🚀 Evaluating kernel autotune results and may create PR."
      EOT