steps:
  # -----------------------------------------------------------------
  # TEST STEPS - Calling wrapper, using python3 -m pytest
  # -----------------------------------------------------------------
   - label: "TPU Daily Test 0: E2E vLLM MLPerf Benchmarking Run on LLaMA3.1 8B (MMLU) with many prompts"
     key: tpu_daily_test_0
     soft_fail: true
     env:
       TPU_BACKEND_TYPE: "jax"
     agents:
       queue: tpu_v6e_queue
     commands:
       - .buildkite/scripts/run_in_docker.sh bash /workspace/tpu_commons/tests/e2e/benchmarking/llama3.1_8b_mmlu_many_prompt.sh

  # -----------------------------------------------------------------
  # NOTIFICATION STEP
  # -----------------------------------------------------------------
   - label: "TPU V1 Test Notification"
     depends_on:
       - tpu_daily_test_0
     agents:
       queue: tpu_v6e_queue
     commands: "bash .buildkite/scripts/check_results.sh daily"
