steps:
  # -----------------------------------------------------------------
  # TEST STEPS - Calling wrapper
  # -----------------------------------------------------------------
   - label: "E2E MLPerf tests for JAX models"
     key: test_0
     soft_fail: true
     env:
       TPU_BACKEND_TYPE: "jax"
     agents:
       queue: tpu_v6e_queue
     commands:
       - .buildkite/scripts/run_in_docker.sh bash /workspace/tpu_commons/tests/e2e/benchmarking/mlperf.sh

   - label: "E2E MLPerf tests for JAX + vLLM models"
     key: test_1
     soft_fail: true
     env:
       TPU_BACKEND_TYPE: "jax"
       MODEL_IMPL_TYPE: "vllm"
     agents:
       queue: tpu_v6e_queue
     commands:
       - .buildkite/scripts/run_in_docker.sh bash /workspace/tpu_commons/tests/e2e/benchmarking/mlperf.sh

  # A placeholder for adding more JAX workload unit tests
   - label: "JAX unit tests"
     key: test_2
     soft_fail: true
     env:
       TPU_BACKEND_TYPE: "jax"
     agents:
       queue: tpu_v6e_queue
     commands:
       - |
         .buildkite/scripts/run_in_docker.sh \
           python3 -m pytest -s -v /workspace/tpu_commons/tests/ --cov tpu_commons --cov-report term-missing

  # -----------------------------------------------------------------
  # NOTIFICATION STEP
  # -----------------------------------------------------------------
   - label: "TPU Test Notification"
     depends_on:
       - test_0
       - test_1
       - test_2
     agents:
       queue: tpu_v6e_queue
     commands: "bash .buildkite/scripts/check_results.sh 'TPU JAX Tests Failed' test_0 test_1 test_2"
