# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  - label: "Task 1 (Priority ${JOB_PRIORITY:-1})"
    priority: ${JOB_PRIORITY:-1}
    commands:
      - echo "Running Task 1... sleep 10s"
      - sleep 10
    agents:
      queue: "cpu"

  - label: "Task 2 (Priority ${JOB_PRIORITY:-1})"
    priority: ${JOB_PRIORITY:-1}
    commands:
      - sleep 10
    agents:
      queue: "cpu"

  - label: "Task 3 (Priority ${JOB_PRIORITY:-1})"
    priority: ${JOB_PRIORITY:-1}
    commands:
      - sleep 10
    agents:
      queue: "cpu"

  - label: "Task 4 (Priority ${JOB_PRIORITY:-1})"
    priority: ${JOB_PRIORITY:-1}
    commands:
      - sleep 10
    agents:
      queue: "cpu"

  - label: "Task 5 (Priority ${JOB_PRIORITY:-1})"
    priority: ${JOB_PRIORITY:-1}
    commands:
      - sleep 10
    agents:
      queue: "cpu"

  - label: "Task 6 (Priority ${JOB_PRIORITY:-1})"
    priority: ${JOB_PRIORITY:-1}
    commands:
      - sleep 10
    agents:
      queue: "cpu"

  - label: "Task 7 (Priority ${JOB_PRIORITY:-1})"
    priority: ${JOB_PRIORITY:-1}
    commands:
      - sleep 10
    agents:
      queue: "cpu"

  - label: "Task 8 (Priority ${JOB_PRIORITY:-1})"
    priority: ${JOB_PRIORITY:-1}
    commands:
      - sleep 10
    agents:
      queue: "cpu"

  - label: "Task 9 (Priority ${JOB_PRIORITY:-1})"
    priority: ${JOB_PRIORITY:-1}
    commands:
      - sleep 10
    agents:
      queue: "cpu"

  - label: "Task 10 (Priority ${JOB_PRIORITY:-1})"
    priority: ${JOB_PRIORITY:-1}
    commands:
      - sleep 10
    agents:
      queue: "cpu"

  - label: "Task 11 (Priority ${JOB_PRIORITY:-1})"
    priority: ${JOB_PRIORITY:-1}
    commands:
      - sleep 10
    agents:
      queue: "cpu"

  - label: "Task 12 (Priority ${JOB_PRIORITY:-1})"
    priority: ${JOB_PRIORITY:-1}
    commands:
      - sleep 10
    agents:
      queue: "cpu"

  - label: "Task 13 (Priority ${JOB_PRIORITY:-1})"
    priority: ${JOB_PRIORITY:-1}
    commands:
      - sleep 10
    agents:
      queue: "cpu"

  - label: "Task 14 (Priority ${JOB_PRIORITY:-1})"
    priority: ${JOB_PRIORITY:-1}
    commands:
      - sleep 10
    agents:
      queue: "cpu"

  - label: "Task 15 (Priority ${JOB_PRIORITY:-1})"
    priority: ${JOB_PRIORITY:-1}
    commands:
      - sleep 10
    agents:
      queue: "cpu"

  - label: "Task 16 (Priority ${JOB_PRIORITY:-1})"
    priority: ${JOB_PRIORITY:-1}
    commands:
      - sleep 10
    agents:
      queue: "cpu"

  - label: "Task 17 (Priority ${JOB_PRIORITY:-1})"
    priority: ${JOB_PRIORITY:-1}
    commands:
      - sleep 10
    agents:
      queue: "cpu"

  - label: "Task 18 (Priority ${JOB_PRIORITY:-1})"
    priority: ${JOB_PRIORITY:-1}
    commands:
      - sleep 10
    agents:
      queue: "cpu"

  - label: "Task 19 (Priority ${JOB_PRIORITY:-1})"
    priority: ${JOB_PRIORITY:-1}
    commands:
      - sleep 10
    agents:
      queue: "cpu"

  - label: "Task 20 (Priority ${JOB_PRIORITY:-1})"
    priority: ${JOB_PRIORITY:-1}
    commands:
      - sleep 10
    agents:
      queue: "cpu"