name: 🤗 Support request for a new model from huggingface
description: Submit a proposal/request for a new model from huggingface
title: "[New Model]: "
labels: ["new model"]

body:
- type: markdown
  attributes:
    value: >
      #### Before submitting an issue, please make sure the issue hasn't been already addressed by searching through [the existing and past issues](https://github.com/vllm-project/tpu-inference/issues?q=is%3Aissue+sort%3Acreated-desc+).

      #### We also highly recommend you read https://github.com/vllm-project/tpu-inference/blob/main/CONTRIBUTING.md first to understand how to add a new model.
- type: textarea
  attributes:
    label: The model to consider.
    description: >
      A huggingface url, pointing to the model, e.g. https://huggingface.co/openai-community/gpt2 .
  validations:
    required: true
- type: textarea
  attributes:
    label: The closest model TPU Inference already supports.
    description: >
      Here is the list of models already supported by TPU Inference: https://github.com/vllm-project/tpu-inference/blob/main/support_matrices/model_support_matrix.csv . Which model is the most similar to the model you want to add support for?
- type: textarea
  attributes:
    label: What's your difficulty of supporting the model you want?
    description: >
      For example, any new operators or new architecture?
- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!
- type: checkboxes
  id: askllm
  attributes:
    label: Before submitting a new issue...
    options:
      - label: Make sure you already searched for relevant issues and checked [documentation page](https://github.com/vllm-project/tpu-inference/tree/main/docs), which can answer lots of frequently asked questions.
        required: true
