# qwix:
#   rules:
#     # NOTE: each entry corresponds to a qwix.QuantizationRule
#     - module_path: '.*'
#       weight_qtype: 'int8'
#       act_qtype: 'int8'
qwix:
  use_abstract_model: True
  scale_dtype": "bfloat16"
  rules:
    # NOTE: each entry corresponds to a qwix.QuantizationRule
    - module_path: 'layers.*.custom_module.kernel_gating_EDF'
      weight_qtype: 'float8_e4m3fn'
      act_qtype: 'float8_e4m3fn'
    - module_path: 'layers.*.custom_module.kernel_up_proj_EDF'
      weight_qtype: 'float8_e4m3fn'
      act_qtype: 'float8_e4m3fn'
    - module_path: 'layers.*.custom_module.kernel_down_proj_EFD'
      weight_qtype: 'float8_e4m3fn'
      act_qtype: 'float8_e4m3fn' #double check