apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hyperdisk-balanced
provisioner: pd.csi.storage.gke.io # The name of the provisioner (CSI driver)
parameters:
  type: hyperdisk-balanced # Specifies a balanced disk type on GCP
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer 
