# FP8 W8A16
# quantization support matrix
steps:
  - label: "${TEST_LABEL_PREFIX} Correctness tests for FP8 W8A16"
    key: "${TEST_KEY_PREFIX}FP8_W8A16_CorrectnessTest"
    soft_fail: true
    agents:
      queue: "${TPU_SMALL_CORE_QUEUE}"
    env:
      IS_FOR_V7X: "${IS_FOR_V7X}"
    commands:
      - |
        buildkite-agent meta-data set "FP8_W8A16_CorrectnessTest" "to be added"
  - label: "${TEST_LABEL_PREFIX} Record correctness test result for FP8 W8A16"
    key: "${TEST_KEY_PREFIX}record_FP8_W8A16_CorrectnessTest"
    depends_on: "${TEST_KEY_PREFIX}FP8_W8A16_CorrectnessTest"
    env:
      CI_TARGET: "${TEST_LABEL_PREFIX} FP8 W8A16"
      CI_STAGE: "CorrectnessTest"
      CI_CATEGORY: "quantization support matrix"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TEST_KEY_PREFIX}FP8_W8A16_CorrectnessTest

  - label: "${TEST_LABEL_PREFIX} Performance tests for FP8 W8A16"
    key: "${TEST_KEY_PREFIX}FP8_W8A16_PerformanceTest"
    depends_on: "${TEST_KEY_PREFIX}record_FP8_W8A16_CorrectnessTest"
    soft_fail: true
    agents:
      queue: "${TPU_SMALL_CORE_QUEUE}"
    env:
      IS_FOR_V7X: "${IS_FOR_V7X}"
    commands:
      - |
        buildkite-agent meta-data set "FP8_W8A16_PerformanceTest" "to be added"
  - label: "${TEST_LABEL_PREFIX} Record performance test result for FP8 W8A16"
    key: "${TEST_KEY_PREFIX}record_FP8_W8A16_PerformanceTest"
    depends_on: "${TEST_KEY_PREFIX}FP8_W8A16_PerformanceTest"
    env:
      CI_TARGET: "${TEST_LABEL_PREFIX} FP8 W8A16"
      CI_STAGE: "PerformanceTest"
      CI_CATEGORY: "quantization support matrix"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TEST_KEY_PREFIX}FP8_W8A16_PerformanceTest
