qwix:
  rules:
    # NOTE: each entry corresponds to a qwix.QuantizationRule
    - module_path: '.*.custom_module.router.*'
      weight_qtype: null
    - module_path: '.*'
      weight_qtype: 'float8_e4m3'
      act_qtype: 'float8_e4m3'
