qwix:
  # This is needed because we want to quantize the abstract model first and then load the weights
  # in
  use_abstract_model: True
  # This signifies that the scales to be loaded in are in fp32
  scale_dtype: 'float32'
  rules:
    # NOTE: each entry corresponds to a qwix.QuantizationRule
    - module_path: '.*.custom_module.router.*'
      weight_qtype: null
    - module_path: '.*'
      weight_qtype: 'float8_e4m3fn'
      act_qtype: 'float8_e4m3fn'
