qwix:
  rules:
    # NOTE: each entry corresponds to a qwix.QuantizationRule
    - module_path: '.attn.'
      weight_qtype: null
    - module_path: '.*'
      weight_qtype: 'int8'
      act_qtype: 'int8'
