#!/bin/bash
set -euo pipefail

echo "--- Post-command hook triggered ---"

if [ -n "${EXECUTE_MODEL:-}" ] && \
   [ -n "${EXECUTE_STAGE:-}" ] && \
   [[ "${BUILDKITE_STEP_KEY:-}" == "notifications_"* ]]; then

    echo "Test exited with status: $BUILDKITE_COMMAND_EXIT_STATUS"

    # If all conditions are true, execute the logic here.
    echo "EXECUTE_MODEL: $EXECUTE_MODEL"
    echo "EXECUTE_STAGE: $EXECUTE_STAGE"
    echo "BUILDKITE_STEP_KEY: $BUILDKITE_STEP_KEY"
    
    if [ "$BUILDKITE_COMMAND_EXIT_STATUS" -eq 0 ]; then
      echo "The step passed. Uploading $EXECUTE_MODEL:$EXECUTE_STAGE result..."
      buildkite-agent meta-data set "$EXECUTE_MODEL:$EXECUTE_STAGE" "passed"
    else
      echo "The step failed. Uploading $EXECUTE_MODEL:$EXECUTE_STAGE result..."
      buildkite-agent meta-data set "$EXECUTE_MODEL:$EXECUTE_STAGE" "failed"
    fi

else
    # If any condition is false, print a message and exit.
    echo "One or more conditions were not met. Skipping execution."
fi