# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: tpu-offline-inference-multihost
spec:
  replicas: 1
  leaderWorkerTemplate:
    size: 2
    restartPolicy: None
    leaderTemplate:
      metadata:
        labels:
          role: leader
      spec:
        serviceAccountName: <your-service-account>
        nodeSelector:
          cloud.google.com/gke-tpu-accelerator: tpu7x
          cloud.google.com/gke-tpu-topology: 2x2x2
        containers:
          - name: vllm-leader
            image: <your-tpu-inference-container-image>
            imagePullPolicy: Always
            env:
            - name: SKIP_JAX_PRECOMPILE
              value: "0"
            - name: TPU_MULTIHOST_BACKEND
              value: ray
            - name: RAY_RESERVE_CPU_FOR_RAYLET
              value: "1"
            - name: RAY_health_check_failure_threshold
              value: "100"
            - name: RAY_health_check_timeout_ms
              value: "20000"
            - name: RAY_health_check_period_ms
              value: "10000"
            - name: RAY_num_heartbeats_timeout
              value: "300000"                         # Allow 300 missed heartbeats instead of default 30
            - name: RAY_raylet_heartbeat_timeout_milliseconds
              value: "3000000"                        # Drop ping intervals slightly to minimize chatter
            - name: RAY_grpc_keepalive_timeout_ms
              value: "3000000"
            - name: RAY_CGRAPH_get_timeout
              value: "30000"
            - name: RAY_CGRAPH_submit_timeout
              value: "30000"
            - name: VLLM_TARGET_DEVICE
              value: "tpu"
            - name: TPU_BACKEND_TYPE
              value: jax
            - name: MODEL_IMPL_TYPE
              value: vllm
            - name: JAX_PLATFORMS
              value: ""
            - name: PJRT_DEVICE
              value: "TPU"
            - name: NEW_MODEL_DESIGN
              value: "0"
            # - name: VLLM_LOGGING_LEVEL
            #   value: "DEBUG"
            # - name: RAY_LOGGING_LEVEL
            #   value: "DEBUG"
            # - name: RAY_BACKEND_LOG_LEVEL
            #   value: "debug"
            # - name: RAY_DEDUP_LOGS
            #   value: "0"
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token-secret
                  key: token
            command: ["/bin/sh", "-c"]
            args:
              - |
                # 1. Initialize the multi-node Ray cluster leader
                bash /workspace/vllm/examples/ray_serving/multi-node-serving.sh leader --ray_cluster_size=$(LWS_GROUP_SIZE);

                # 2. Run vLLM serve
                VLLM_DISABLE_SHARED_EXPERTS_STREAM=1 vllm serve --port 8000 \
                  --load-format=runai_streamer \
                  --model=<your-model-path> \
                  --enable-prefix-caching \
                  --async-scheduling \
                  --enable-expert-parallel \
                  --max-model-len 51200 \
                  --enable-chunked-prefill \
                  --seed 42 \
                  --tensor-parallel-size 16 \
                  --gpu-memory-utilization=0.8
            resources:
              limits:
                google.com/tpu: "4"
            ports:
              - containerPort: 8000
            readinessProbe:
              tcpSocket:
                port: 8000
              initialDelaySeconds: 15
              periodSeconds: 10
            volumeMounts:
              - mountPath: /dev/shm
                name: dshm
        volumes:
        - name: dshm
          emptyDir:
            medium: Memory
    workerTemplate:
      spec:
        serviceAccountName: <your-service-account>
        nodeSelector:
          cloud.google.com/gke-tpu-accelerator: tpu7x
          cloud.google.com/gke-tpu-topology: 2x2x2
        containers:
          - name: vllm-worker
            image: <your-tpu-inference-container-image>
            imagePullPolicy: Always
            command: ["/bin/sh", "-c"]
            args:
              - |
                bash /workspace/vllm/examples/ray_serving/multi-node-serving.sh worker --ray_address=$(LWS_LEADER_ADDRESS)
            resources:
              limits:
                google.com/tpu: "4"
            env:
            - name: SKIP_JAX_PRECOMPILE
              value: "0"
            - name: TPU_MULTIHOST_BACKEND
              value: ray
            - name: RAY_RESERVE_CPU_FOR_RAYLET
              value: "1"
            - name: RAY_health_check_failure_threshold
              value: "100"
            - name: RAY_health_check_timeout_ms
              value: "20000"                          # Timeout for each GCS health check ping
            - name: RAY_health_check_period_ms
              value: "10000"                          # Ping interval for GCS health check
            - name: RAY_num_heartbeats_timeout
              value: "300000"                         # Allow 300 missed heartbeats instead of default 30
            - name: RAY_raylet_heartbeat_timeout_milliseconds
              value: "3000000"                        # Drop ping intervals slightly to minimize chatter
            - name: RAY_grpc_keepalive_timeout_ms
              value: "3000000"
            - name: RAY_CGRAPH_get_timeout
              value: "30000"
            - name: RAY_CGRAPH_submit_timeout
              value: "30000"
            - name: VLLM_TARGET_DEVICE
              value: "tpu"
            - name: TPU_BACKEND_TYPE
              value: jax
            - name: MODEL_IMPL_TYPE
              value: vllm
            - name: JAX_PLATFORMS
              value: ""
            - name: PJRT_DEVICE
              value: "TPU"
            - name: NEW_MODEL_DESIGN
              value: "0"
            # - name: VLLM_LOGGING_LEVEL
            #   value: "DEBUG"
            # - name: RAY_LOGGING_LEVEL
            #   value: "DEBUG"
            # - name: RAY_BACKEND_LOG_LEVEL
            #   value: "debug"
            # - name: RAY_DEDUP_LOGS
            #   value: "0"
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token-secret
                  key: token
            volumeMounts:
              - mountPath: /dev/shm
                name: dshm
        volumes:
        - name: dshm
          emptyDir:
            medium: Memory
