# gmm-w4a4
# kernel support matrix microbenchmarks
steps:
  - label: "Correctness tests for gmm-w4a4"
    key: "gmm-w4a4_CorrectnessTest"
    soft_fail: true
    agents:
      queue: tpu_v6e_queue
    commands:
      - |
        buildkite-agent meta-data set "gmm-w4a4_CorrectnessTest" "to be added"
  - label: "Record correctness test result for gmm-w4a4"
    key: "record_gmm-w4a4_CorrectnessTest"
    depends_on: "gmm-w4a4_CorrectnessTest"
    env:
      CI_TARGET: "gmm-w4a4"
      CI_STAGE: "CorrectnessTest"
      CI_CATEGORY: "kernel support matrix microbenchmarks"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh gmm-w4a4_CorrectnessTest

  - label: "Performance tests for gmm-w4a4"
    key: "gmm-w4a4_PerformanceTest"
    depends_on: "record_gmm-w4a4_CorrectnessTest"
    soft_fail: true
    agents:
      queue: tpu_v6e_queue
    commands:
      - |
        buildkite-agent meta-data set "gmm-w4a4_PerformanceTest" "to be added"
  - label: "Record performance test result for gmm-w4a4"
    key: "record_gmm-w4a4_PerformanceTest"
    depends_on: "gmm-w4a4_PerformanceTest"
    env:
      CI_TARGET: "gmm-w4a4"
      CI_STAGE: "PerformanceTest"
      CI_CATEGORY: "kernel support matrix microbenchmarks"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh gmm-w4a4_PerformanceTest
