# all-gather-matmul-w8a8
# kernel support matrix microbenchmarks
steps:
  - label: "Correctness tests for all-gather-matmul-w8a8"
    key: "all-gather-matmul-w8a8_CorrectnessTest"
    soft_fail: true
    agents:
      queue: tpu_v6e_queue
    commands:
      - |
        buildkite-agent meta-data set "all-gather-matmul-w8a8_CorrectnessTest" "to be added"
  - label: "Record correctness test result for all-gather-matmul-w8a8"
    key: "record_all-gather-matmul-w8a8_CorrectnessTest"
    depends_on: "all-gather-matmul-w8a8_CorrectnessTest"
    env:
      CI_TARGET: "all-gather-matmul-w8a8"
      CI_STAGE: "CorrectnessTest"
      CI_CATEGORY: "kernel support matrix microbenchmarks"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh all-gather-matmul-w8a8_CorrectnessTest

  - label: "Performance tests for all-gather-matmul-w8a8"
    key: "all-gather-matmul-w8a8_PerformanceTest"
    depends_on: "record_all-gather-matmul-w8a8_CorrectnessTest"
    soft_fail: true
    agents:
      queue: tpu_v6e_queue
    commands:
      - |
        buildkite-agent meta-data set "all-gather-matmul-w8a8_PerformanceTest" "to be added"
  - label: "Record performance test result for all-gather-matmul-w8a8"
    key: "record_all-gather-matmul-w8a8_PerformanceTest"
    depends_on: "all-gather-matmul-w8a8_PerformanceTest"
    env:
      CI_TARGET: "all-gather-matmul-w8a8"
      CI_STAGE: "PerformanceTest"
      CI_CATEGORY: "kernel support matrix microbenchmarks"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh all-gather-matmul-w8a8_PerformanceTest
