# Auto-generated from print.log
# Each entry corresponds to one line in print.log

import dataclasses

import jax.numpy as jnp

from tpu_inference.kernels.experimental.batched_rpa.configs import (
    BlockSizes,
    ModelConfigs,
    ServingConfigs,
)


@dataclasses.dataclass
class LogEntry:
    model: ModelConfigs
    serve: ServingConfigs
    decode_block_sizes: BlockSizes
    prefill_block_sizes: BlockSizes


LOG_ENTRIES = [
    # Line 1
    LogEntry(
        model=ModelConfigs(
            num_q_heads=16,
            num_kv_heads=8,
            head_dim=256,
            mask_value=-3.38953e+38,
            sliding_window=1024,
        ),
        serve=ServingConfigs(
            num_seqs=64,
            page_size=256,
            total_q_tokens=128,
            num_page_indices=1024,
            dtype_q=jnp.bfloat16,
            dtype_kv=jnp.float8_e4m3fn,
            dtype_out=jnp.bfloat16,
            scale_q=None,
            scale_k=1.0,
            scale_v=1.0,
        ),
        decode_block_sizes=BlockSizes(bq_sz=1, bq_c_sz=1, bkv_sz=256, batch_size=8, n_buffer=3),
        prefill_block_sizes=BlockSizes(bq_sz=256, bq_c_sz=64, bkv_sz=256, batch_size=2, n_buffer=3),
    ),
    # Line 2
    LogEntry(
        model=ModelConfigs(
            num_q_heads=16,
            num_kv_heads=2,
            head_dim=512,
            mask_value=-3.38953e+38,
            sliding_window=None,
        ),
        serve=ServingConfigs(
            num_seqs=64,
            page_size=256,
            total_q_tokens=128,
            num_page_indices=1024,
            dtype_q=jnp.bfloat16,
            dtype_kv=jnp.float8_e4m3fn,
            dtype_out=jnp.bfloat16,
            scale_q=None,
            scale_k=1.0,
            scale_v=1.0,
        ),
        decode_block_sizes=BlockSizes(bq_sz=1, bq_c_sz=1, bkv_sz=768, batch_size=8, n_buffer=3),
        prefill_block_sizes=BlockSizes(bq_sz=256, bq_c_sz=64, bkv_sz=256, batch_size=1, n_buffer=3),
    ),
    # Line 3
    LogEntry(
        model=ModelConfigs(
            num_q_heads=16,
            num_kv_heads=8,
            head_dim=256,
            mask_value=-3.38953e+38,
            sliding_window=1024,
        ),
        serve=ServingConfigs(
            num_seqs=1024,
            page_size=256,
            total_q_tokens=4,
            num_page_indices=6144,
            dtype_q=jnp.bfloat16,
            dtype_kv=jnp.float8_e4m3fn,
            dtype_out=jnp.bfloat16,
            scale_q=None,
            scale_k=1.0,
            scale_v=1.0,
        ),
        decode_block_sizes=BlockSizes(bq_sz=1, bq_c_sz=1, bkv_sz=256, batch_size=8, n_buffer=3),
        prefill_block_sizes=BlockSizes(bq_sz=256, bq_c_sz=64, bkv_sz=256, batch_size=2, n_buffer=3),
    ),
    # Line 4
    LogEntry(
        model=ModelConfigs(
            num_q_heads=16,
            num_kv_heads=2,
            head_dim=512,
            mask_value=-3.38953e+38,
            sliding_window=None,
        ),
        serve=ServingConfigs(
            num_seqs=1024,
            page_size=256,
            total_q_tokens=4,
            num_page_indices=6144,
            dtype_q=jnp.bfloat16,
            dtype_kv=jnp.float8_e4m3fn,
            dtype_out=jnp.bfloat16,
            scale_q=None,
            scale_k=1.0,
            scale_v=1.0,
        ),
        decode_block_sizes=BlockSizes(bq_sz=1, bq_c_sz=1, bkv_sz=768, batch_size=8, n_buffer=3),
        prefill_block_sizes=BlockSizes(bq_sz=256, bq_c_sz=64, bkv_sz=256, batch_size=1, n_buffer=3),
    ),
    # Line 5
    LogEntry(
        model=ModelConfigs(
            num_q_heads=16,
            num_kv_heads=8,
            head_dim=256,
            mask_value=-3.38953e+38,
            sliding_window=1024,
        ),
        serve=ServingConfigs(
            num_seqs=1024,
            page_size=256,
            total_q_tokens=8,
            num_page_indices=6144,
            dtype_q=jnp.bfloat16,
            dtype_kv=jnp.float8_e4m3fn,
            dtype_out=jnp.bfloat16,
            scale_q=None,
            scale_k=1.0,
            scale_v=1.0,
        ),
        decode_block_sizes=BlockSizes(bq_sz=1, bq_c_sz=1, bkv_sz=256, batch_size=8, n_buffer=3),
        prefill_block_sizes=BlockSizes(bq_sz=256, bq_c_sz=64, bkv_sz=256, batch_size=2, n_buffer=3),
    ),
    # Line 6
    LogEntry(
        model=ModelConfigs(
            num_q_heads=16,
            num_kv_heads=2,
            head_dim=512,
            mask_value=-3.38953e+38,
            sliding_window=None,
        ),
        serve=ServingConfigs(
            num_seqs=1024,
            page_size=256,
            total_q_tokens=8,
            num_page_indices=6144,
            dtype_q=jnp.bfloat16,
            dtype_kv=jnp.float8_e4m3fn,
            dtype_out=jnp.bfloat16,
            scale_q=None,
            scale_k=1.0,
            scale_v=1.0,
        ),
        decode_block_sizes=BlockSizes(bq_sz=1, bq_c_sz=1, bkv_sz=768, batch_size=8, n_buffer=3),
        prefill_block_sizes=BlockSizes(bq_sz=256, bq_c_sz=64, bkv_sz=256, batch_size=1, n_buffer=3),
    ),
    # Line 7
    LogEntry(
        model=ModelConfigs(
            num_q_heads=16,
            num_kv_heads=8,
            head_dim=256,
            mask_value=-3.38953e+38,
            sliding_window=1024,
        ),
        serve=ServingConfigs(
            num_seqs=1024,
            page_size=256,
            total_q_tokens=16,
            num_page_indices=6144,
            dtype_q=jnp.bfloat16,
            dtype_kv=jnp.float8_e4m3fn,
            dtype_out=jnp.bfloat16,
            scale_q=None,
            scale_k=1.0,
            scale_v=1.0,
        ),
        decode_block_sizes=BlockSizes(bq_sz=1, bq_c_sz=1, bkv_sz=256, batch_size=8, n_buffer=3),
        prefill_block_sizes=BlockSizes(bq_sz=256, bq_c_sz=64, bkv_sz=256, batch_size=2, n_buffer=3),
    ),
    # Line 8
    LogEntry(
        model=ModelConfigs(
            num_q_heads=16,
            num_kv_heads=2,
            head_dim=512,
            mask_value=-3.38953e+38,
            sliding_window=None,
        ),
        serve=ServingConfigs(
            num_seqs=1024,
            page_size=256,
            total_q_tokens=16,
            num_page_indices=6144,
            dtype_q=jnp.bfloat16,
            dtype_kv=jnp.float8_e4m3fn,
            dtype_out=jnp.bfloat16,
            scale_q=None,
            scale_k=1.0,
            scale_v=1.0,
        ),
        decode_block_sizes=BlockSizes(bq_sz=1, bq_c_sz=1, bkv_sz=768, batch_size=8, n_buffer=3),
        prefill_block_sizes=BlockSizes(bq_sz=256, bq_c_sz=64, bkv_sz=256, batch_size=1, n_buffer=3),
    ),
    # Line 9
    LogEntry(
        model=ModelConfigs(
            num_q_heads=16,
            num_kv_heads=8,
            head_dim=256,
            mask_value=-3.38953e+38,
            sliding_window=1024,
        ),
        serve=ServingConfigs(
            num_seqs=1024,
            page_size=256,
            total_q_tokens=32,
            num_page_indices=6144,
            dtype_q=jnp.bfloat16,
            dtype_kv=jnp.float8_e4m3fn,
            dtype_out=jnp.bfloat16,
            scale_q=None,
            scale_k=1.0,
            scale_v=1.0,
        ),
        decode_block_sizes=BlockSizes(bq_sz=1, bq_c_sz=1, bkv_sz=256, batch_size=8, n_buffer=3),
        prefill_block_sizes=BlockSizes(bq_sz=256, bq_c_sz=64, bkv_sz=256, batch_size=2, n_buffer=3),
    ),
    # Line 10
    LogEntry(
        model=ModelConfigs(
            num_q_heads=16,
            num_kv_heads=2,
            head_dim=512,
            mask_value=-3.38953e+38,
            sliding_window=None,
        ),
        serve=ServingConfigs(
            num_seqs=1024,
            page_size=256,
            total_q_tokens=32,
            num_page_indices=6144,
            dtype_q=jnp.bfloat16,
            dtype_kv=jnp.float8_e4m3fn,
            dtype_out=jnp.bfloat16,
            scale_q=None,
            scale_k=1.0,
            scale_v=1.0,
        ),
        decode_block_sizes=BlockSizes(bq_sz=1, bq_c_sz=1, bkv_sz=768, batch_size=8, n_buffer=3),
        prefill_block_sizes=BlockSizes(bq_sz=256, bq_c_sz=64, bkv_sz=256, batch_size=1, n_buffer=3),
    ),
    # Line 11
    LogEntry(
        model=ModelConfigs(
            num_q_heads=16,
            num_kv_heads=8,
            head_dim=256,
            mask_value=-3.38953e+38,
            sliding_window=1024,
        ),
        serve=ServingConfigs(
            num_seqs=1024,
            page_size=256,
            total_q_tokens=64,
            num_page_indices=6144,
            dtype_q=jnp.bfloat16,
            dtype_kv=jnp.float8_e4m3fn,
            dtype_out=jnp.bfloat16,
            scale_q=None,
            scale_k=1.0,
            scale_v=1.0,
        ),
        decode_block_sizes=BlockSizes(bq_sz=1, bq_c_sz=1, bkv_sz=256, batch_size=8, n_buffer=3),
        prefill_block_sizes=BlockSizes(bq_sz=256, bq_c_sz=64, bkv_sz=256, batch_size=2, n_buffer=3),
    ),
    # Line 12
    LogEntry(
        model=ModelConfigs(
            num_q_heads=16,
            num_kv_heads=2,
            head_dim=512,
            mask_value=-3.38953e+38,
            sliding_window=None,
        ),
        serve=ServingConfigs(
            num_seqs=1024,
            page_size=256,
            total_q_tokens=64,
            num_page_indices=6144,
            dtype_q=jnp.bfloat16,
            dtype_kv=jnp.float8_e4m3fn,
            dtype_out=jnp.bfloat16,
            scale_q=None,
            scale_k=1.0,
            scale_v=1.0,
        ),
        decode_block_sizes=BlockSizes(bq_sz=1, bq_c_sz=1, bkv_sz=768, batch_size=8, n_buffer=3),
        prefill_block_sizes=BlockSizes(bq_sz=256, bq_c_sz=64, bkv_sz=256, batch_size=1, n_buffer=3),
    ),
    # Line 13
    LogEntry(
        model=ModelConfigs(
            num_q_heads=16,
            num_kv_heads=8,
            head_dim=256,
            mask_value=-3.38953e+38,
            sliding_window=1024,
        ),
        serve=ServingConfigs(
            num_seqs=1024,
            page_size=256,
            total_q_tokens=128,
            num_page_indices=6144,
            dtype_q=jnp.bfloat16,
            dtype_kv=jnp.float8_e4m3fn,
            dtype_out=jnp.bfloat16,
            scale_q=None,
            scale_k=1.0,
            scale_v=1.0,
        ),
        decode_block_sizes=BlockSizes(bq_sz=1, bq_c_sz=1, bkv_sz=256, batch_size=8, n_buffer=3),
        prefill_block_sizes=BlockSizes(bq_sz=256, bq_c_sz=64, bkv_sz=256, batch_size=2, n_buffer=3),
    ),
    # Line 14
    LogEntry(
        model=ModelConfigs(
            num_q_heads=16,
            num_kv_heads=2,
            head_dim=512,
            mask_value=-3.38953e+38,
            sliding_window=None,
        ),
        serve=ServingConfigs(
            num_seqs=1024,
            page_size=256,
            total_q_tokens=128,
            num_page_indices=6144,
            dtype_q=jnp.bfloat16,
            dtype_kv=jnp.float8_e4m3fn,
            dtype_out=jnp.bfloat16,
            scale_q=None,
            scale_k=1.0,
            scale_v=1.0,
        ),
        decode_block_sizes=BlockSizes(bq_sz=1, bq_c_sz=1, bkv_sz=768, batch_size=8, n_buffer=3),
        prefill_block_sizes=BlockSizes(bq_sz=256, bq_c_sz=64, bkv_sz=256, batch_size=1, n_buffer=3),
    ),
    # Line 15
    LogEntry(
        model=ModelConfigs(
            num_q_heads=16,
            num_kv_heads=8,
            head_dim=256,
            mask_value=-3.38953e+38,
            sliding_window=1024,
        ),
        serve=ServingConfigs(
            num_seqs=1024,
            page_size=256,
            total_q_tokens=256,
            num_page_indices=6144,
            dtype_q=jnp.bfloat16,
            dtype_kv=jnp.float8_e4m3fn,
            dtype_out=jnp.bfloat16,
            scale_q=None,
            scale_k=1.0,
            scale_v=1.0,
        ),
        decode_block_sizes=BlockSizes(bq_sz=1, bq_c_sz=1, bkv_sz=256, batch_size=8, n_buffer=3),
        prefill_block_sizes=BlockSizes(bq_sz=256, bq_c_sz=64, bkv_sz=256, batch_size=2, n_buffer=3),
    ),
    # Line 16
    LogEntry(
        model=ModelConfigs(
            num_q_heads=16,
            num_kv_heads=2,
            head_dim=512,
            mask_value=-3.38953e+38,
            sliding_window=None,
        ),
        serve=ServingConfigs(
            num_seqs=1024,
            page_size=256,
            total_q_tokens=256,
            num_page_indices=6144,
            dtype_q=jnp.bfloat16,
            dtype_kv=jnp.float8_e4m3fn,
            dtype_out=jnp.bfloat16,
            scale_q=None,
            scale_k=1.0,
            scale_v=1.0,
        ),
        decode_block_sizes=BlockSizes(bq_sz=1, bq_c_sz=1, bkv_sz=768, batch_size=8, n_buffer=3),
        prefill_block_sizes=BlockSizes(bq_sz=256, bq_c_sz=64, bkv_sz=256, batch_size=1, n_buffer=3),
    ),
    # Line 17
    LogEntry(
        model=ModelConfigs(
            num_q_heads=16,
            num_kv_heads=8,
            head_dim=256,
            mask_value=-3.38953e+38,
            sliding_window=1024,
        ),
        serve=ServingConfigs(
            num_seqs=1024,
            page_size=256,
            total_q_tokens=512,
            num_page_indices=6144,
            dtype_q=jnp.bfloat16,
            dtype_kv=jnp.float8_e4m3fn,
            dtype_out=jnp.bfloat16,
            scale_q=None,
            scale_k=1.0,
            scale_v=1.0,
        ),
        decode_block_sizes=BlockSizes(bq_sz=1, bq_c_sz=1, bkv_sz=256, batch_size=8, n_buffer=3),
        prefill_block_sizes=BlockSizes(bq_sz=256, bq_c_sz=64, bkv_sz=256, batch_size=2, n_buffer=3),
    ),
    # Line 18
    LogEntry(
        model=ModelConfigs(
            num_q_heads=16,
            num_kv_heads=2,
            head_dim=512,
            mask_value=-3.38953e+38,
            sliding_window=None,
        ),
        serve=ServingConfigs(
            num_seqs=1024,
            page_size=256,
            total_q_tokens=512,
            num_page_indices=6144,
            dtype_q=jnp.bfloat16,
            dtype_kv=jnp.float8_e4m3fn,
            dtype_out=jnp.bfloat16,
            scale_q=None,
            scale_k=1.0,
            scale_v=1.0,
        ),
        decode_block_sizes=BlockSizes(bq_sz=1, bq_c_sz=1, bkv_sz=768, batch_size=8, n_buffer=3),
        prefill_block_sizes=BlockSizes(bq_sz=256, bq_c_sz=64, bkv_sz=256, batch_size=1, n_buffer=3),
    ),
    # Line 19
    LogEntry(
        model=ModelConfigs(
            num_q_heads=16,
            num_kv_heads=8,
            head_dim=256,
            mask_value=-3.38953e+38,
            sliding_window=1024,
        ),
        serve=ServingConfigs(
            num_seqs=1024,
            page_size=256,
            total_q_tokens=1024,
            num_page_indices=6144,
            dtype_q=jnp.bfloat16,
            dtype_kv=jnp.float8_e4m3fn,
            dtype_out=jnp.bfloat16,
            scale_q=None,
            scale_k=1.0,
            scale_v=1.0,
        ),
        decode_block_sizes=BlockSizes(bq_sz=1, bq_c_sz=1, bkv_sz=256, batch_size=8, n_buffer=3),
        prefill_block_sizes=BlockSizes(bq_sz=256, bq_c_sz=64, bkv_sz=256, batch_size=2, n_buffer=3),
    ),
    # Line 20
    LogEntry(
        model=ModelConfigs(
            num_q_heads=16,
            num_kv_heads=2,
            head_dim=512,
            mask_value=-3.38953e+38,
            sliding_window=None,
        ),
        serve=ServingConfigs(
            num_seqs=1024,
            page_size=256,
            total_q_tokens=1024,
            num_page_indices=6144,
            dtype_q=jnp.bfloat16,
            dtype_kv=jnp.float8_e4m3fn,
            dtype_out=jnp.bfloat16,
            scale_q=None,
            scale_k=1.0,
            scale_v=1.0,
        ),
        decode_block_sizes=BlockSizes(bq_sz=1, bq_c_sz=1, bkv_sz=768, batch_size=8, n_buffer=3),
        prefill_block_sizes=BlockSizes(bq_sz=256, bq_c_sz=64, bkv_sz=256, batch_size=1, n_buffer=3),
    ),
    # Line 21
    LogEntry(
        model=ModelConfigs(
            num_q_heads=16,
            num_kv_heads=8,
            head_dim=256,
            mask_value=-3.38953e+38,
            sliding_window=1024,
        ),
        serve=ServingConfigs(
            num_seqs=1024,
            page_size=256,
            total_q_tokens=2048,
            num_page_indices=6144,
            dtype_q=jnp.bfloat16,
            dtype_kv=jnp.float8_e4m3fn,
            dtype_out=jnp.bfloat16,
            scale_q=None,
            scale_k=1.0,
            scale_v=1.0,
        ),
        decode_block_sizes=BlockSizes(bq_sz=1, bq_c_sz=1, bkv_sz=256, batch_size=8, n_buffer=3),
        prefill_block_sizes=BlockSizes(bq_sz=256, bq_c_sz=64, bkv_sz=256, batch_size=2, n_buffer=3),
    ),
    # Line 22
    LogEntry(
        model=ModelConfigs(
            num_q_heads=16,
            num_kv_heads=2,
            head_dim=512,
            mask_value=-3.38953e+38,
            sliding_window=None,
        ),
        serve=ServingConfigs(
            num_seqs=1024,
            page_size=256,
            total_q_tokens=2048,
            num_page_indices=6144,
            dtype_q=jnp.bfloat16,
            dtype_kv=jnp.float8_e4m3fn,
            dtype_out=jnp.bfloat16,
            scale_q=None,
            scale_k=1.0,
            scale_v=1.0,
        ),
        decode_block_sizes=BlockSizes(bq_sz=1, bq_c_sz=1, bkv_sz=768, batch_size=8, n_buffer=3),
        prefill_block_sizes=BlockSizes(bq_sz=256, bq_c_sz=64, bkv_sz=256, batch_size=1, n_buffer=3),
    ),
    # Line 23
    LogEntry(
        model=ModelConfigs(
            num_q_heads=16,
            num_kv_heads=8,
            head_dim=256,
            mask_value=-3.38953e+38,
            sliding_window=1024,
        ),
        serve=ServingConfigs(
            num_seqs=1024,
            page_size=256,
            total_q_tokens=4096,
            num_page_indices=6144,
            dtype_q=jnp.bfloat16,
            dtype_kv=jnp.float8_e4m3fn,
            dtype_out=jnp.bfloat16,
            scale_q=None,
            scale_k=1.0,
            scale_v=1.0,
        ),
        decode_block_sizes=BlockSizes(bq_sz=1, bq_c_sz=1, bkv_sz=256, batch_size=8, n_buffer=3),
        prefill_block_sizes=BlockSizes(bq_sz=256, bq_c_sz=64, bkv_sz=256, batch_size=2, n_buffer=3),
    ),
    # Line 24
    LogEntry(
        model=ModelConfigs(
            num_q_heads=16,
            num_kv_heads=2,
            head_dim=512,
            mask_value=-3.38953e+38,
            sliding_window=None,
        ),
        serve=ServingConfigs(
            num_seqs=1024,
            page_size=256,
            total_q_tokens=4096,
            num_page_indices=6144,
            dtype_q=jnp.bfloat16,
            dtype_kv=jnp.float8_e4m3fn,
            dtype_out=jnp.bfloat16,
            scale_q=None,
            scale_k=1.0,
            scale_v=1.0,
        ),
        decode_block_sizes=BlockSizes(bq_sz=1, bq_c_sz=1, bkv_sz=768, batch_size=8, n_buffer=3),
        prefill_block_sizes=BlockSizes(bq_sz=256, bq_c_sz=64, bkv_sz=256, batch_size=1, n_buffer=3),
    ),
    # Line 25
    LogEntry(
        model=ModelConfigs(
            num_q_heads=16,
            num_kv_heads=8,
            head_dim=256,
            mask_value=-3.38953e+38,
            sliding_window=1024,
        ),
        serve=ServingConfigs(
            num_seqs=1024,
            page_size=256,
            total_q_tokens=8192,
            num_page_indices=6144,
            dtype_q=jnp.bfloat16,
            dtype_kv=jnp.float8_e4m3fn,
            dtype_out=jnp.bfloat16,
            scale_q=None,
            scale_k=1.0,
            scale_v=1.0,
        ),
        decode_block_sizes=BlockSizes(bq_sz=1, bq_c_sz=1, bkv_sz=256, batch_size=8, n_buffer=3),
        prefill_block_sizes=BlockSizes(bq_sz=256, bq_c_sz=64, bkv_sz=256, batch_size=2, n_buffer=3),
    ),
    # Line 26
    LogEntry(
        model=ModelConfigs(
            num_q_heads=16,
            num_kv_heads=2,
            head_dim=512,
            mask_value=-3.38953e+38,
            sliding_window=None,
        ),
        serve=ServingConfigs(
            num_seqs=1024,
            page_size=256,
            total_q_tokens=8192,
            num_page_indices=6144,
            dtype_q=jnp.bfloat16,
            dtype_kv=jnp.float8_e4m3fn,
            dtype_out=jnp.bfloat16,
            scale_q=None,
            scale_k=1.0,
            scale_v=1.0,
        ),
        decode_block_sizes=BlockSizes(bq_sz=1, bq_c_sz=1, bkv_sz=768, batch_size=8, n_buffer=3),
        prefill_block_sizes=BlockSizes(bq_sz=256, bq_c_sz=64, bkv_sz=256, batch_size=1, n_buffer=3),
    ),
    # Line 27
    LogEntry(
        model=ModelConfigs(
            num_q_heads=16,
            num_kv_heads=8,
            head_dim=256,
            mask_value=-3.38953e+38,
            sliding_window=1024,
        ),
        serve=ServingConfigs(
            num_seqs=1024,
            page_size=256,
            total_q_tokens=16384,
            num_page_indices=6144,
            dtype_q=jnp.bfloat16,
            dtype_kv=jnp.float8_e4m3fn,
            dtype_out=jnp.bfloat16,
            scale_q=None,
            scale_k=1.0,
            scale_v=1.0,
        ),
        decode_block_sizes=BlockSizes(bq_sz=1, bq_c_sz=1, bkv_sz=256, batch_size=8, n_buffer=3),
        prefill_block_sizes=BlockSizes(bq_sz=256, bq_c_sz=64, bkv_sz=256, batch_size=2, n_buffer=3),
    ),
    # Line 28
    LogEntry(
        model=ModelConfigs(
            num_q_heads=16,
            num_kv_heads=2,
            head_dim=512,
            mask_value=-3.38953e+38,
            sliding_window=None,
        ),
        serve=ServingConfigs(
            num_seqs=1024,
            page_size=256,
            total_q_tokens=16384,
            num_page_indices=6144,
            dtype_q=jnp.bfloat16,
            dtype_kv=jnp.float8_e4m3fn,
            dtype_out=jnp.bfloat16,
            scale_q=None,
            scale_k=1.0,
            scale_v=1.0,
        ),
        decode_block_sizes=BlockSizes(bq_sz=1, bq_c_sz=1, bkv_sz=768, batch_size=8, n_buffer=3),
        prefill_block_sizes=BlockSizes(bq_sz=256, bq_c_sz=64, bkv_sz=256, batch_size=1, n_buffer=3),
    ),
]
