# deepseek-ai/DeepSeek-V3.1
# text-only
steps:
  - label: "${TEST_LABEL_PREFIX} Unit tests for deepseek-ai/DeepSeek-V3.1"
    key: "${TEST_KEY_PREFIX}deepseek-ai_DeepSeek-V3_1_UnitTest"
    agents:
      queue: "${TPU_LARGE_CORE_QUEUE}"
    env:
      IS_FOR_V7X: "${IS_FOR_V7X}"
    soft_fail: true
    commands:
      - |
        buildkite-agent meta-data set "${TEST_KEY_PREFIX}deepseek-ai_DeepSeek-V3_1_UnitTest" "unverified"
  - label: "${TEST_LABEL_PREFIX} Record unit test result for deepseek-ai/DeepSeek-V3.1"
    key: "${TEST_KEY_PREFIX}record_deepseek-ai_DeepSeek-V3_1_UnitTest"
    depends_on: "${TEST_KEY_PREFIX}deepseek-ai_DeepSeek-V3_1_UnitTest"
    env:
      CI_TARGET: "${TEST_LABEL_PREFIX}deepseek-ai/DeepSeek-V3.1"
      CI_STAGE: "UnitTest"
      CI_CATEGORY: "text-only"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TEST_KEY_PREFIX}deepseek-ai_DeepSeek-V3_1_UnitTest

  - label: "${TEST_LABEL_PREFIX} Integration tests for deepseek-ai/DeepSeek-V3.1"
    key: "${TEST_KEY_PREFIX}deepseek-ai_DeepSeek-V3_1_IntegrationTest"
    depends_on: "${TEST_KEY_PREFIX}record_deepseek-ai_DeepSeek-V3_1_UnitTest"
    agents:
      queue: "${TPU_LARGE_CORE_QUEUE}"
    env:
      IS_FOR_V7X: "${IS_FOR_V7X}"
    soft_fail: true
    commands:
      - |
        buildkite-agent meta-data set "${TEST_KEY_PREFIX}deepseek-ai_DeepSeek-V3_1_IntegrationTest" "unverified"
  - label: "${TEST_LABEL_PREFIX} Record integration test result for deepseek-ai/DeepSeek-V3.1"
    key: "${TEST_KEY_PREFIX}record_deepseek-ai_DeepSeek-V3_1_IntegrationTest"
    depends_on: "${TEST_KEY_PREFIX}deepseek-ai_DeepSeek-V3_1_IntegrationTest"
    env:
      CI_TARGET: "${TEST_LABEL_PREFIX}deepseek-ai/DeepSeek-V3.1"
      CI_STAGE: "IntegrationTest"
      CI_CATEGORY: "text-only"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TEST_KEY_PREFIX}deepseek-ai_DeepSeek-V3_1_IntegrationTest

  - label: "${TEST_LABEL_PREFIX} Performance benchmarks for deepseek-ai/DeepSeek-V3.1"
    key: "${TEST_KEY_PREFIX}deepseek-ai_DeepSeek-V3_1_Benchmark"
    depends_on: "${TEST_KEY_PREFIX}record_deepseek-ai_DeepSeek-V3_1_IntegrationTest"
    agents:
      queue: "${TPU_LARGE_CORE_QUEUE}"
    env:
      IS_FOR_V7X: "${IS_FOR_V7X}"
    soft_fail: true
    commands:
      - |
        buildkite-agent meta-data set "${TEST_KEY_PREFIX}deepseek-ai_DeepSeek-V3_1_Benchmark" "unverified"
  - label: "${TEST_LABEL_PREFIX} Record performance benchmark result for deepseek-ai/DeepSeek-V3.1"
    key: "${TEST_KEY_PREFIX}record_deepseek-ai_DeepSeek-V3_1_Benchmark"
    depends_on: "${TEST_KEY_PREFIX}deepseek-ai_DeepSeek-V3_1_Benchmark"
    env:
      CI_TARGET: "${TEST_LABEL_PREFIX}deepseek-ai/DeepSeek-V3.1"
      CI_STAGE: "Benchmark"
      CI_CATEGORY: "text-only"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TEST_KEY_PREFIX}deepseek-ai_DeepSeek-V3_1_Benchmark
