# meta-llama/Llama-3.1-8B-Instruct
agents:
  queue: tpu_v6e_queue
steps:
  - label: "Unit tests for meta-llama/Llama-3.1-8B-Instruct"
    key: "ut_meta-llama_Llama-3_1-8B-Instruct"
    commands:
      # - replace_with_test_commands  # TODO: Replaced to actual test commands
      - echo "[DEBUG], unit testing for meta-llama/Llama-3.1-8B-Instruct"  # TODO: Replace to actual test commands
  - label: "Notifications: Unit tests for meta-llama/Llama-3.1-8B-Instruct"
    key: "notifications_ut_meta-llama_Llama-3_1-8B-Instruct"
    depends_on: "ut_meta-llama_Llama-3_1-8B-Instruct"
    agents:
      queue: tpu_v6e_queue
    env:
      EXECUTE_MODEL: "meta-llama/Llama-3.1-8B-Instruct"
      EXECUTE_STAGE: "UnitTest"
    commands:
      - |
        .buildkite/scripts/check_results.sh \
          "Unit tests for meta-llama/Llama-3.1-8B-Instruct" ut_meta-llama_Llama-3_1-8B-Instruct
    plugins:
      - ".buildkite": ~

  - label: "Integration tests for meta-llama/Llama-3.1-8B-Instruct"
    key: "it_meta-llama_Llama-3_1-8B-Instruct"
    depends_on: "notifications_ut_meta-llama_Llama-3_1-8B-Instruct"
    commands:
      # TODO: expected_accuracy need parameterized
      # - .buildkite/scripts/run_in_docker.sh bash /workspace/tpu_commons/tests/e2e/benchmarking/test_accuracy.sh -t 1 -m "meta-llama/Llama-3.1-8B-Instruct"
      - echo "[DEBUG], integration testing for meta-llama/Llama-3.1-8B-Instruct"  # TODO: Replace to actual test commands
  - label: "Notifications: Integration tests for meta-llama/Llama-3.1-8B-Instruct"
    key: "notifications_it_meta-llama_Llama-3_1-8B-Instruct"
    depends_on: "it_meta-llama_Llama-3_1-8B-Instruct"
    agents:
      queue: tpu_v6e_queue
    commands:
      - |
        .buildkite/scripts/check_results.sh \
          "Integration tests for meta-llama/Llama-3.1-8B-Instruct" it_meta-llama_Llama-3_1-8B-Instruct

  - label: "Performance benchmarks for meta-llama/Llama-3.1-8B-Instruct"
    key: "pb_meta-llama_Llama-3_1-8B-Instruct"
    depends_on: "notifications_it_meta-llama_Llama-3_1-8B-Instruct"
    commands:
      # - replace_with_test_command  # TODO
      - echo "[DEBUG], performance benchmarking for meta-llama/Llama-3.1-8B-Instruct"  # TODO: Replace to actual test commands
  - label: "Notifications: Performance benchmarks for meta-llama/Llama-3.1-8B-Instruct"
    key: "notifications_pb_meta-llama_Llama-3_1-8B-Instruct"
    depends_on: "pb_meta-llama_Llama-3_1-8B-Instruct"
    agents:
      queue: tpu_v6e_queue
    commands:
      - |
        .buildkite/scripts/check_results.sh \
          "Performance benchmarks for meta-llama/Llama-3.1-8B-Instruct" pb_meta-llama_Llama-3_1-8B-Instruct

  - label: "Stress tests for meta-llama/Llama-3.1-8B-Instruct"
    key: "st_meta-llama_Llama-3_1-8B-Instruct"
    depends_on: "notifications_pb_meta-llama_Llama-3_1-8B-Instruct"
    commands:
      # - our_stress_tests_script meta-llama/Llama-3.1-8B-Instruct expected_throughput # TODO: expected_throughput need parameterized
      - echo "[DEBUG], stress testing for meta-llama/Llama-3.1-8B-Instruct"  # TODO: Replace to actual test commands
  - label: "Notifications: Stress tests for meta-llama/Llama-3.1-8B-Instruct"
    key: "notifications_st_meta-llama_Llama-3_1-8B-Instruct"
    depends_on: "st_meta-llama_Llama-3_1-8B-Instruct"
    agents:
      queue: tpu_v6e_queue
    commands:
      - |
        .buildkite/scripts/check_results.sh \
          "Stress tests for meta-llama/Llama-3.1-8B-Instruct" st_meta-llama_Llama-3_1-8B-Instruct
