# meta-llama/Llama-4-Maverick-17B-128E-Instruct
# multimodal
steps:
  - label: "${TEST_LABEL_PREFIX} Unit tests for meta-llama/Llama-4-Maverick-17B-128E-Instruct"
    key: "${TEST_KEY_PREFIX}meta-llama_Llama-4-Maverick-17B-128E-Instruct_UnitTest"
    agents:
      queue: "${TPU_LARGE_CORE_QUEUE}"
    env:
      IS_FOR_V7X: "${IS_FOR_V7X}"
    soft_fail: true
    commands:
      - |
        buildkite-agent meta-data set "${TEST_KEY_PREFIX}meta-llama_Llama-4-Maverick-17B-128E-Instruct_UnitTest" "unverified"
  - label: "${TEST_LABEL_PREFIX} Record unit test result for meta-llama/Llama-4-Maverick-17B-128E-Instruct"
    key: "${TEST_KEY_PREFIX}record_meta-llama_Llama-4-Maverick-17B-128E-Instruct_UnitTest"
    depends_on: "${TEST_KEY_PREFIX}meta-llama_Llama-4-Maverick-17B-128E-Instruct_UnitTest"
    env:
      CI_TARGET: "${TEST_LABEL_PREFIX}meta-llama/Llama-4-Maverick-17B-128E-Instruct"
      CI_STAGE: "UnitTest"
      CI_CATEGORY: "multimodal"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TEST_KEY_PREFIX}meta-llama_Llama-4-Maverick-17B-128E-Instruct_UnitTest

  - label: "${TEST_LABEL_PREFIX} Integration tests for meta-llama/Llama-4-Maverick-17B-128E-Instruct"
    key: "${TEST_KEY_PREFIX}meta-llama_Llama-4-Maverick-17B-128E-Instruct_IntegrationTest"
    depends_on: "${TEST_KEY_PREFIX}record_meta-llama_Llama-4-Maverick-17B-128E-Instruct_UnitTest"
    agents:
      queue: "${TPU_LARGE_CORE_QUEUE}"
    env:
      IS_FOR_V7X: "${IS_FOR_V7X}"
    soft_fail: true
    commands:
      - |
        buildkite-agent meta-data set "${TEST_KEY_PREFIX}meta-llama_Llama-4-Maverick-17B-128E-Instruct_IntegrationTest" "unverified"
  - label: "${TEST_LABEL_PREFIX} Record integration test result for meta-llama/Llama-4-Maverick-17B-128E-Instruct"
    key: "${TEST_KEY_PREFIX}record_meta-llama_Llama-4-Maverick-17B-128E-Instruct_IntegrationTest"
    depends_on: "${TEST_KEY_PREFIX}meta-llama_Llama-4-Maverick-17B-128E-Instruct_IntegrationTest"
    env:
      CI_TARGET: "${TEST_LABEL_PREFIX}meta-llama/Llama-4-Maverick-17B-128E-Instruct"
      CI_STAGE: "IntegrationTest"
      CI_CATEGORY: "multimodal"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TEST_KEY_PREFIX}meta-llama_Llama-4-Maverick-17B-128E-Instruct_IntegrationTest

  - label: "${TEST_LABEL_PREFIX} Performance benchmarks for meta-llama/Llama-4-Maverick-17B-128E-Instruct"
    key: "${TEST_KEY_PREFIX}meta-llama_Llama-4-Maverick-17B-128E-Instruct_Benchmark"
    depends_on: "${TEST_KEY_PREFIX}record_meta-llama_Llama-4-Maverick-17B-128E-Instruct_IntegrationTest"
    agents:
      queue: "${TPU_LARGE_CORE_QUEUE}"
    env:
      IS_FOR_V7X: "${IS_FOR_V7X}"
    soft_fail: true
    commands:
      - |
        buildkite-agent meta-data set "${TEST_KEY_PREFIX}meta-llama_Llama-4-Maverick-17B-128E-Instruct_Benchmark" "unverified"
  - label: "${TEST_LABEL_PREFIX} Record performance benchmark result for meta-llama/Llama-4-Maverick-17B-128E-Instruct"
    key: "${TEST_KEY_PREFIX}record_meta-llama_Llama-4-Maverick-17B-128E-Instruct_Benchmark"
    depends_on: "${TEST_KEY_PREFIX}meta-llama_Llama-4-Maverick-17B-128E-Instruct_Benchmark"
    env:
      CI_TARGET: "${TEST_LABEL_PREFIX}meta-llama/Llama-4-Maverick-17B-128E-Instruct"
      CI_STAGE: "Benchmark"
      CI_CATEGORY: "multimodal"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TEST_KEY_PREFIX}meta-llama_Llama-4-Maverick-17B-128E-Instruct_Benchmark
