# meta-llama/Llama-3.1-8B-Instruct
# text-only
steps:
  - label: "Unit tests for meta-llama/Llama-3.1-8B-Instruct"
    key: "meta-llama_Llama-3_1-8B-Instruct_UnitTest"
    agents:
      queue: tpu_v6e_queue
    soft_fail: true
    commands:
      - echo "placeholder"  # TODO: replace with your unit test command
  - label: "Record unit test result for meta-llama/Llama-3.1-8B-Instruct"
    key: "record_meta-llama_Llama-3_1-8B-Instruct_UnitTest"
    depends_on: "meta-llama_Llama-3_1-8B-Instruct_UnitTest"
    env:
      CI_TARGET: meta-llama/Llama-3.1-8B-Instruct
      CI_STAGE: "UnitTest"
      CI_CATEGORY: "text-only"
    agents:
      queue: tpu_v6e_queue
    commands:
      - |
        .buildkite/scripts/record_step_result.sh meta-llama_Llama-3_1-8B-Instruct_UnitTest

  - label: "Integration tests for meta-llama/Llama-3.1-8B-Instruct"
    key: "meta-llama_Llama-3_1-8B-Instruct_IntegrationTest"
    depends_on: "record_meta-llama_Llama-3_1-8B-Instruct_UnitTest"
    agents:
      queue: tpu_v6e_queue
    soft_fail: true
    env:
      TEST_MODEL: meta-llama/Llama-3.1-8B-Instruct
      TENSOR_PARALLEL_SIZE: 1
      MINIMUM_ACCURACY_THRESHOLD: 1  # TODO : replace 0 with your accuracy threshold
    commands:
      - |
        .buildkite/scripts/run_in_docker.sh bash /workspace/tpu_inference/tests/e2e/benchmarking/test_accuracy.sh
  - label: "Record integration test result for meta-llama/Llama-3.1-8B-Instruct"
    key: "record_meta-llama_Llama-3_1-8B-Instruct_IntegrationTest"
    depends_on: "meta-llama_Llama-3_1-8B-Instruct_IntegrationTest"
    env:
      CI_TARGET: meta-llama/Llama-3.1-8B-Instruct
      CI_STAGE: "IntegrationTest"
      CI_CATEGORY: "text-only"
    agents:
      queue: tpu_v6e_queue
    commands:
      - |
        .buildkite/scripts/record_step_result.sh meta-llama_Llama-3_1-8B-Instruct_IntegrationTest
