# meta-llama/Llama-Guard-4-12B
steps:
  - label: "Unit tests for meta-llama/Llama-Guard-4-12B"
    key: "meta-llama_Llama-Guard-4-12B_UnitTest"
    agents:
      queue: tpu_v6e_queue
    soft_fail: true
    commands:
      - |
        .buildkite/scripts/run_in_docker.sh \
          bash -c 'python3 -m pytest -s -v -x /workspace/tpu_inference/tests/models/jax/test_llama_guard_4.py'
  - label: "Record unit test result for meta-llama/Llama-Guard-4-12B"
    key: "record_meta-llama_Llama-Guard-4-12B_UnitTest"
    depends_on: "meta-llama_Llama-Guard-4-12B_UnitTest"
    env:
      CI_STAGE: "UnitTest"
      CI_TARGET: meta-llama/Llama-Guard-4-12B
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh meta-llama_Llama-Guard-4-12B_UnitTest

  - label: "Integration tests for meta-llama/Llama-Guard-4-12B"
    key: "meta-llama_Llama-Guard-4-12B_IntegrationTest"
    depends_on: "record_meta-llama_Llama-Guard-4-12B_UnitTest"
    agents:
      queue: tpu_v6e_queue
    soft_fail: true
    env:
      TEST_MODEL: meta-llama/Llama-Guard-4-12B
      TENSOR_PARALLEL_SIZE: 8
      MINIMUM_ACCURACY_THRESHOLD: 0.31
    commands:
      - |
        .buildkite/scripts/run_in_docker.sh bash /workspace/tpu_inference/tests/e2e/benchmarking/test_llama_guard_4_accuracy.sh
  - label: "Record integration test result for meta-llama/Llama-Guard-4-12B"
    key: "record_meta-llama_Llama-Guard-4-12B_IntegrationTest"
    depends_on: "meta-llama_Llama-Guard-4-12B_IntegrationTest"
    env:
      CI_TARGET: meta-llama/Llama-Guard-4-12B
      CI_STAGE: "IntegrationTest"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh meta-llama_Llama-Guard-4-12B_IntegrationTest
    
  - label: "Performance benchmarks for meta-llama/Llama-Guard-4-12B"
    key: "meta-llama_Llama-Guard-4-12B_Benchmark"
    depends_on: "record_meta-llama_Llama-Guard-4-12B_IntegrationTest"
    soft_fail: true
    agents:
      queue: tpu_v6e_queue 
    commands:
      - |
        .buildkite/scripts/run_in_docker.sh bash /workspace/tpu_inference/tests/e2e/benchmarking/llama_guard_perf_recipe.sh
  
  - label: "Record performance benchmark result for meta-llama/Llama-Guard-4-12B"
    key: "record_meta-llama_Llama-Guard-4-12B_Benchmark"
    depends_on: "meta-llama_Llama-Guard-4-12B_Benchmark"
    env:
      CI_TARGET: meta-llama/Llama-Guard-4-12B
      CI_STAGE: "Benchmark"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh meta-llama_Llama-Guard-4-12B_Benchmark
