# meta-llama/Llama-4-Maverick-17B-128E-Instruct
# multimodal
steps:
  - label: "Unit tests for meta-llama/Llama-4-Maverick-17B-128E-Instruct"
    key: "meta-llama_Llama-4-Maverick-17B-128E-Instruct_UnitTest"
    agents:
      queue: tpu_v6e_8_queue
    soft_fail: true
    commands:
      - |
        buildkite-agent meta-data set "meta-llama_Llama-4-Maverick-17B-128E-Instruct_UnitTest" "unverified"
  - label: "Record unit test result for meta-llama/Llama-4-Maverick-17B-128E-Instruct"
    key: "record_meta-llama_Llama-4-Maverick-17B-128E-Instruct_UnitTest"
    depends_on: "meta-llama_Llama-4-Maverick-17B-128E-Instruct_UnitTest"
    env:
      CI_TARGET: meta-llama/Llama-4-Maverick-17B-128E-Instruct
      CI_STAGE: "UnitTest"
      CI_CATEGORY: "multimodal"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh meta-llama_Llama-4-Maverick-17B-128E-Instruct_UnitTest

  - label: "Integration tests for meta-llama/Llama-4-Maverick-17B-128E-Instruct"
    key: "meta-llama_Llama-4-Maverick-17B-128E-Instruct_IntegrationTest"
    depends_on: "record_meta-llama_Llama-4-Maverick-17B-128E-Instruct_UnitTest"
    agents:
      queue: tpu_v6e_8_queue
    soft_fail: true
    commands:
      - |
        buildkite-agent meta-data set "meta-llama_Llama-4-Maverick-17B-128E-Instruct_IntegrationTest" "unverified"
  - label: "Record integration test result for meta-llama/Llama-4-Maverick-17B-128E-Instruct"
    key: "record_meta-llama_Llama-4-Maverick-17B-128E-Instruct_IntegrationTest"
    depends_on: "meta-llama_Llama-4-Maverick-17B-128E-Instruct_IntegrationTest"
    env:
      CI_TARGET: meta-llama/Llama-4-Maverick-17B-128E-Instruct
      CI_STAGE: "IntegrationTest"
      CI_CATEGORY: "multimodal"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh meta-llama_Llama-4-Maverick-17B-128E-Instruct_IntegrationTest

  - label: "Performance benchmarks for meta-llama/Llama-4-Maverick-17B-128E-Instruct"
    key: "meta-llama_Llama-4-Maverick-17B-128E-Instruct_Benchmark"
    depends_on: "record_meta-llama_Llama-4-Maverick-17B-128E-Instruct_IntegrationTest"
    agents:
      queue: tpu_v6e_8_queue
    soft_fail: true
    commands:
      - |
        buildkite-agent meta-data set "meta-llama_Llama-4-Maverick-17B-128E-Instruct_Benchmark" "unverified"
  - label: "Record performance benchmark result for meta-llama/Llama-4-Maverick-17B-128E-Instruct"
    key: "record_meta-llama_Llama-4-Maverick-17B-128E-Instruct_Benchmark"
    depends_on: "meta-llama_Llama-4-Maverick-17B-128E-Instruct_Benchmark"
    env:
      CI_TARGET: meta-llama/Llama-4-Maverick-17B-128E-Instruct
      CI_STAGE: "Benchmark"
      CI_CATEGORY: "multimodal"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh meta-llama_Llama-4-Maverick-17B-128E-Instruct_Benchmark
