# Qwen/Qwen3-Coder-480B-A35B-Instruct
# text-only
steps:
  - label: "Unit tests for Qwen/Qwen3-Coder-480B-A35B-Instruct"
    key: "Qwen_Qwen3-Coder-480B-A35B-Instruct_UnitTest"
    agents:
      queue: tpu_v6e_8_queue
    soft_fail: true
    commands:
      - |
        buildkite-agent meta-data set "Qwen_Qwen3-Coder-480B-A35B-Instruct_UnitTest" "unverified"
  - label: "Record unit test result for Qwen/Qwen3-Coder-480B-A35B-Instruct"
    key: "record_Qwen_Qwen3-Coder-480B-A35B-Instruct_UnitTest"
    depends_on: "Qwen_Qwen3-Coder-480B-A35B-Instruct_UnitTest"
    env:
      CI_TARGET: Qwen/Qwen3-Coder-480B-A35B-Instruct
      CI_STAGE: "UnitTest"
      CI_CATEGORY: "text-only"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh Qwen_Qwen3-Coder-480B-A35B-Instruct_UnitTest

  - label: "Integration tests for Qwen/Qwen3-Coder-480B-A35B-Instruct"
    key: "Qwen_Qwen3-Coder-480B-A35B-Instruct_IntegrationTest"
    depends_on: "record_Qwen_Qwen3-Coder-480B-A35B-Instruct_UnitTest"
    agents:
      queue: tpu_v6e_8_queue
    soft_fail: true
    commands:
      - |
        buildkite-agent meta-data set "Qwen_Qwen3-Coder-480B-A35B-Instruct_IntegrationTest" "unverified"
  - label: "Record integration test result for Qwen/Qwen3-Coder-480B-A35B-Instruct"
    key: "record_Qwen_Qwen3-Coder-480B-A35B-Instruct_IntegrationTest"
    depends_on: "Qwen_Qwen3-Coder-480B-A35B-Instruct_IntegrationTest"
    env:
      CI_TARGET: Qwen/Qwen3-Coder-480B-A35B-Instruct
      CI_STAGE: "IntegrationTest"
      CI_CATEGORY: "text-only"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh Qwen_Qwen3-Coder-480B-A35B-Instruct_IntegrationTest

  - label: "Performance benchmarks for Qwen/Qwen3-Coder-480B-A35B-Instruct"
    key: "Qwen_Qwen3-Coder-480B-A35B-Instruct_Benchmark"
    depends_on: "record_Qwen_Qwen3-Coder-480B-A35B-Instruct_IntegrationTest"
    agents:
      queue: tpu_v6e_8_queue
    soft_fail: true
    commands:
      - |
        buildkite-agent meta-data set "Qwen_Qwen3-Coder-480B-A35B-Instruct_Benchmark" "unverified"
  - label: "Record performance benchmark result for Qwen/Qwen3-Coder-480B-A35B-Instruct"
    key: "record_Qwen_Qwen3-Coder-480B-A35B-Instruct_Benchmark"
    depends_on: "Qwen_Qwen3-Coder-480B-A35B-Instruct_Benchmark"
    env:
      CI_TARGET: Qwen/Qwen3-Coder-480B-A35B-Instruct
      CI_STAGE: "Benchmark"
      CI_CATEGORY: "text-only"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh Qwen_Qwen3-Coder-480B-A35B-Instruct_Benchmark
