# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

env:
  GCP_PROJECT_ID: "cloud-tpu-inference-test"
  GCP_REGION: "southamerica-west1"
  GCS_BUCKET: "vllm-cb-storage2"
  ARTIFACT_REPO: "vllm-tpu-bm-bk"
  GCP_INSTANCE_ID: "vllm-bm-inst"
  GCP_DATABASE_ID: "vllm-bm-bk-runs"

definitions:
  base_env_0: &base_env_0
    DEVICE: "tpu7x-8"
    MODEL: "deepseek-ai/DeepSeek-R1"
    MAX_NUM_SEQS: "128"
    MAX_NUM_BATCHED_TOKENS: "1024"
    TENSOR_PARALLEL_SIZE: "8"
    DATASET: "mmlu"
    VLLM_MLA_DISABLE: "1"
    NEW_MODEL_DESIGN: "True"
    TPU_BACKEND_TYPE: "jax"
    ADDITIONAL_CONFIG: '""'

  base_cfg_0: &base_cfg_0
    depends_on: "build-vllm-tpu-image"
    agents:
      queue: "tpu_v7x_8_queue"
    command: ".buildkite/benchmark/scripts/run_job_from_env.sh"
steps:
  - label: "Benchmark - deepseek-ai/DeepSeek-R1-datset_mmlu-inlen_1800-outlen_128 RecordId: bk-${BUILDKITE_STEP_ID}"
    <<: *base_cfg_0
    env:
      <<: *base_env_0
      INPUT_LEN: "1800"
      OUTPUT_LEN: "128"
      MAX_MODEL_LEN: "2048"
      PREFIX_LEN: "0"
